"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Result={type:"order"|"customer"|"address"|"invoice";id:string;title:string;subtitle:string;href:string};
const labels={order:"订单",customer:"客户",address:"地址",invoice:"Invoice"};

export default function SearchPage(){
  const [query,setQuery]=useState(""),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false),[error,setError]=useState("");
  async function run(value=query){const q=value.trim();if(q.length<2){setError("请至少输入 2 个字符");return}setLoading(true);setError("");setSearched(true);try{const response=await fetch(`/api/v4/search?q=${encodeURIComponent(q)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"搜索失败");setResults(data.results||[]);history.replaceState(null,"",`/search?q=${encodeURIComponent(q)}`)}catch(reason){setResults([]);setError(reason instanceof Error?reason.message:"搜索失败")}finally{setLoading(false)}}
  const submit=(event:FormEvent)=>{event.preventDefault();void run()};
  return <main className="page"><header><div><small>BRAUN SMART PORTAL · GLOBAL SEARCH</small><h1>全局搜索 <span>Global Search</span></h1><p>一次查找当前账号有权查看的真实订单、客户、Invoice、电话、邮箱和地址。</p></div><Link href="/hub">返回统一门户</Link></header>
    <form onSubmit={submit}><input autoFocus aria-label="全局搜索" value={query} onChange={event=>setQuery(event.target.value)} placeholder="输入 68735、CWF68735、客户、电话、邮箱或地址"/><button disabled={loading}>{loading?"搜索中…":"搜索"}</button></form>
    {error&&<div className="error">{error}</div>}<section className="results">{results.map(result=><Link className="result" href={result.href} key={`${result.type}-${result.id}`}><span className="type">{labels[result.type]}</span><div><strong>{result.title}</strong><p>{result.subtitle||"—"}</p></div><b>打开 →</b></Link>)}{loading&&<div className="empty">正在搜索真实数据库…</div>}{searched&&!loading&&!error&&!results.length&&<div className="empty">没有找到当前账号可访问的记录</div>}{!searched&&<div className="empty">输入关键词开始搜索。Tracking 会在物流正式数据接入后加入。</div>}</section>
    <style jsx>{`.page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:30px;font-family:Arial,"PingFang SC",sans-serif}header,form,.error,.results{max-width:1150px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;gap:20px}h1{font-size:36px;margin:7px 0}h1 span{font-weight:400;color:#6c7974}small,p{color:#687871}header a,button{border:0;border-radius:10px;padding:12px 17px;background:#1f5b49;color:white;text-decoration:none;font-weight:800;height:max-content}form{display:grid;grid-template-columns:1fr auto;gap:10px;margin-top:25px}input{box-sizing:border-box;width:100%;border:1px solid #c8d4ce;border-radius:12px;padding:15px;font-size:16px;background:white}.error{box-sizing:border-box;margin-top:15px;background:#fff0ec;color:#963c31;padding:13px;border-radius:10px}.results{display:grid;gap:10px;margin-top:16px}.result{display:grid;grid-template-columns:90px 1fr auto;gap:15px;align-items:center;background:white;border:1px solid #dedbd3;border-radius:14px;padding:16px;text-decoration:none;color:#18352c}.result p{margin:5px 0 0}.type{background:#e6efe9;color:#1f5b49;border-radius:999px;padding:6px 9px;text-align:center;font-size:12px;font-weight:800}.result>b{color:#1f5b49}.empty{text-align:center;padding:45px;background:white;border:1px dashed #cfd6d2;border-radius:14px;color:#74817b}button:disabled{opacity:.5}@media(max-width:650px){.page{padding:15px}header{display:block}header a{display:inline-block;margin-top:10px}form{grid-template-columns:1fr}.result{grid-template-columns:70px 1fr}.result>b{display:none}}`}</style></main>;
}
