"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type WindowRow={id:number;code:string;measurements:unknown[]};
type Snapshot={property:{name:string;customerId:number|null};room:{name:string};window:{code:string};measurement:{id:number;version:number};design:{id:number;version:number;combinationType:string};fabrics:{versionId:number;sku:string}[];hardware:{id:number;sku:string}[];qaRunId:number};
type Handoff={id:number;revision:number;status:string;sourceHash:string;createdAt:string};
type State={ready?:boolean;missing?:string[];changed?:boolean;impact?:string[];sourceHash?:string;snapshot?:Snapshot;handoffs?:Handoff[];error?:string};
const stages=["AI Visualizer","Quote","Customer Approval","Order","Production Drawing"];

export default function WorkflowHandoffPage(){
  const[windows,setWindows]=useState<WindowRow[]>([]),[windowId,setWindowId]=useState(0),[state,setState]=useState<State>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=async(id:number)=>{if(!id)return;const response=await fetch(`/api/v4/workflow-handoff?windowId=${id}`,{cache:"no-store"});const data=await response.json();setState(data);if(!response.ok)setMessage(data.error||"Unable to load workflow")};
  useEffect(()=>{fetch("/api/v4/design-studio",{cache:"no-store"}).then(r=>r.json()).then(data=>{const rows=(data.windows||[]).filter((w:WindowRow)=>w.measurements?.length);setWindows(rows);const id=rows[0]?.id||0;setWindowId(id);void load(id)})},[]);
  const prepare=async()=>{setBusy(true);setMessage("");const key=`handoff-${crypto.randomUUID()}-${crypto.randomUUID()}`;const response=await fetch("/api/v4/workflow-handoff",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({windowId})});const data=await response.json();setBusy(false);setMessage(response.ok?`Revision ${data.handoff.revision} prepared — all five artifacts reference the same locked snapshot.`:data.error||(data.missing||[]).join(", "));await load(windowId)};
  const s=state.snapshot;
  return <main className="page"><header><div><small>SPRINT 8 · ONE-CLICK HANDOFF #146</small><h1>一键业务流转 / One-click Handoff</h1><p>同一 Property、Room、Window、批准测量和设计版本只生成一份权威快照；所有下游业务只引用，不重复录入。</p></div><nav><Link href="/measure-qa">QA</Link><Link href="/design-studio">Design</Link><Link href="/hub">Hub</Link></nav></header>
  <section className="card toolbar"><label>Window<select value={windowId} onChange={e=>{const id=+e.target.value;setWindowId(id);setMessage("");void load(id)}}>{windows.map(w=><option key={w.id} value={w.id}>{w.code} · #{w.id}</option>)}</select></label><button disabled={!state.ready||busy} onClick={()=>void prepare()}>{busy?"Preparing…":state.changed?"Create controlled revision":"Prepare five linked artifacts"}</button></section>
  {message&&<p className="message">{message}</p>}{state.error&&<section className="card blocked">{state.error}</section>}{state.missing&&<section className="card blocked"><h2>Not ready / 尚未满足</h2>{state.missing.map(x=><p key={x}>• {x}</p>)}</section>}
  {s&&<><section className="card identities"><h2>Authoritative source identity</h2><div><b>Property</b><span>{s.property.name}</span><small>Customer #{s.property.customerId||"—"}</small></div><div><b>Room / Window</b><span>{s.room.name} / {s.window.code}</span><small>Permanent Window #{windowId}</small></div><div><b>Measurement</b><span>V{s.measurement.version}</span><small>ID #{s.measurement.id} · approved</small></div><div><b>Design</b><span>V{s.design.version}</span><small>{s.design.combinationType} · ID #{s.design.id}</small></div><div><b>QA</b><span>Run #{s.qaRunId}</span><small>No open errors</small></div><div><b>Exact materials</b><span>{s.fabrics.map(x=>`${x.sku} · FV#${x.versionId}`).join(", ")||"No fabric"}</span><small>{s.hardware.map(x=>`${x.sku} · #${x.id}`).join(", ")||"No hardware"}</small></div></section>
  <section className="card pipeline"><h2>Locked downstream chain</h2>{stages.map((stage,index)=><div key={stage}><span>{index+1}</span><b>{stage}</b><small>same source hash</small></div>)}</section>
  {state.changed&&<section className="card impact"><h2>Change impact preview / 变更影响</h2><p>源记录已与上一版不同。系统不会覆盖旧版，确认后将创建新 revision。</p>{state.impact?.map(x=><li key={x}>{x}</li>)}</section>}
  <section className="card hash"><b>Source SHA-256</b><code>{state.sourceHash}</code></section></>}
  <section className="card history"><h2>Traceability / 流转历史</h2>{!state.handoffs?.length&&<p>No handoff revision yet.</p>}{state.handoffs?.map(h=><article key={h.id}><b>Revision {h.revision}</b><span>{h.status}</span><code>{h.sourceHash.slice(0,16)}…</code><time>{new Date(h.createdAt).toLocaleString()}</time></article>)}</section><style jsx>{styles}</style></main>;
}
const styles=`.page{min-height:100vh;background:#f3f0e9;color:#20372f;padding:20px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.message{max-width:1200px;margin:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:25px;display:flex;justify-content:space-between}header p{color:#c8d9d2;max-width:780px}nav{display:flex;gap:8px;align-items:start}a,button{border:0;border-radius:9px;padding:10px 12px;background:#dfb45c;color:#173f35;text-decoration:none;font-weight:800}.card{margin-top:14px;background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px}.toolbar{display:flex;gap:14px;align-items:end}.toolbar label{display:grid;gap:6px;flex:1;font-weight:800}.toolbar select{padding:12px;border:1px solid #bdc9c3;border-radius:9px}.toolbar button{background:#1e6650;color:white}.toolbar button:disabled{opacity:.45}.message{margin-top:12px;padding:12px;background:#e6f2eb;border-radius:10px}.blocked{border-left:8px solid #b24839}.identities{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.identities h2{grid-column:1/-1}.identities div{display:grid;gap:5px;background:#f5f7f4;padding:13px;border-radius:10px}.identities span{font-size:18px}.identities small{color:#67736e}.pipeline{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.pipeline h2{grid-column:1/-1}.pipeline div{display:grid;text-align:center;gap:6px;background:#e9f2ed;border-radius:12px;padding:15px}.pipeline span{margin:auto;background:#1f654f;color:white;width:28px;height:28px;border-radius:50%;display:grid;place-items:center}.impact{border-left:8px solid #d9a33c}.hash{display:grid;gap:7px}.hash code{word-break:break-all;color:#52635c}.history article{display:grid;grid-template-columns:130px 100px 1fr auto;gap:12px;border-top:1px solid #e3e5e1;padding:12px 0}.history span{text-transform:uppercase}.history code{color:#63736c}@media(max-width:760px){.page{padding:10px}header{flex-direction:column}.toolbar{align-items:stretch;flex-direction:column}.identities,.pipeline{grid-template-columns:1fr}.identities h2,.pipeline h2{grid-column:1}.history article{grid-template-columns:1fr 1fr}.history time{grid-column:1/-1}}`;
