"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { formatSixteenths } from "@/lib/measurement-sixteenths";

type Order = { orderNumber:string;externalPrefix:string;projectName:string;projectAddress:string;status:string;paymentStatus?:string;currency:string;grandTotal?:number;amountPaid?:number;balanceDue?:number;updatedAt:string };
type Customer = { companyName:string;contactName:string;email:string;phone:string };
type Item = { id:number;productType:string;style:string;fabricCode:string;width:number|null;height:number|null;widthSixteenths:number|null;heightSixteenths:number|null;quantity:number;mountType:string;controlType:string;lining:string;unitPrice?:number;lineTotal?:number;costEstimateUsd?:number|null;notes:string };

export default function OrderWorkspacePage({params}:{params:Promise<{orderNumber:string}>}) {
  const {orderNumber}=use(params),[order,setOrder]=useState<Order|null>(null),[customer,setCustomer]=useState<Customer|null>(null),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/v4/orders/${encodeURIComponent(orderNumber)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load order");setOrder(data.order);setCustomer(data.customer);setItems(data.items||[])}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load order")}finally{setLoading(false)}},[orderNumber]);
  // Initial route load synchronizes the workspace with the protected order API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  if(loading)return <main className="state">正在读取真实订单…</main>;
  if(error||!order)return <main className="state"><p>{error||"Order not found"}</p><Link href="/orders">返回订单中心</Link></main>;
  return <main className="page"><header><div><small>ORDER WORKSPACE / 订单工作区</small><h1>{order.externalPrefix?`${order.externalPrefix} `:""}{order.orderNumber}</h1><p>{customer?.companyName||customer?.contactName||"—"} · {order.projectName||"未填写项目名称"}</p></div><div className="actions"><Link href="/orders">← 订单列表</Link><button onClick={()=>void load()}>刷新</button></div></header>
    <section className="overview"><article><span>订单状态</span><b>{order.status}</b></article><article><span>付款状态</span><b>{order.paymentStatus||"受权限保护"}</b></article><article><span>订单总额</span><b>{order.grandTotal===undefined?"受权限保护":`${order.currency} ${order.grandTotal.toFixed(2)}`}</b></article><article><span>应付余额</span><b>{order.balanceDue===undefined?"受权限保护":`${order.currency} ${order.balanceDue.toFixed(2)}`}</b></article></section>
    <div className="grid"><section className="card"><h2>客户与项目 <span>Customer & Project</span></h2><dl><div><dt>公司</dt><dd>{customer?.companyName||"—"}</dd></div><div><dt>联系人</dt><dd>{customer?.contactName||"—"}</dd></div><div><dt>电话</dt><dd>{customer?.phone||"—"}</dd></div><div><dt>邮箱</dt><dd>{customer?.email||"—"}</dd></div><div><dt>工程地址</dt><dd>{order.projectAddress||"—"}</dd></div></dl></section><section className="card"><h2>产品明细 <span>Order Items</span></h2><p>共 {items.length} 条；确认后的订单必须通过版本或调整流程修改。</p></section></div>
    <section className="card items"><div className="table"><table><thead><tr><th>产品</th><th>款式 / 面料</th><th>尺寸</th><th>数量</th><th>安装 / 控制</th><th>金额</th><th>备注</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>{item.productType}</b></td><td>{item.style||"—"}<small>{item.fabricCode||"—"}</small></td><td>{item.widthSixteenths===null||item.heightSixteenths===null?item.width===null||item.height===null?"—":`${item.width} × ${item.height} in`:`${formatSixteenths(item.widthSixteenths)} × ${formatSixteenths(item.heightSixteenths)}`}</td><td>{item.quantity}</td><td>{item.mountType||"—"}<small>{item.controlType||item.lining||"—"}</small></td><td>{item.lineTotal===undefined?"受权限保护":`${order.currency} ${item.lineTotal.toFixed(2)}`}</td><td>{item.notes||"—"}</td></tr>)}</tbody></table>{!items.length&&<div className="empty">暂无产品明细 / No order items</div>}</div></section>
    <footer>最后更新：{new Date(order.updatedAt).toLocaleString()} · 数据来自统一订单数据库</footer>
    <style jsx>{`.page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:30px;font-family:Arial,"PingFang SC",sans-serif}header,.overview,.grid,.card,footer{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;gap:18px}.actions{display:flex;gap:10px;align-items:flex-start}a,button{border:0;border-radius:9px;padding:10px 14px;background:#1f5b49;color:white;text-decoration:none;font-weight:800}h1{font-size:38px;margin:6px 0}small,h2 span,p,dt{color:#687871}.overview{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:22px}.overview article,.card{background:white;border:1px solid #dedbd3;border-radius:16px;padding:18px}.overview span{display:block;font-size:12px}.overview b{display:block;margin-top:8px;font-size:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.card{margin-top:14px}h2{margin-top:0}h2 span{font-weight:400;font-size:15px}dl div{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-bottom:1px solid #eeeae3}dd{margin:0;text-align:right;font-weight:700}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:950px}th,td{padding:12px;border-bottom:1px solid #e8e5de;text-align:left;font-size:13px}.empty{text-align:center;padding:30px;color:#75817c}footer{padding:22px 0;color:#718078;font-size:12px}.state{min-height:100vh;display:grid;place-content:center;text-align:center;gap:12px;background:#f4f2ed;color:#18352c;font-family:Arial,"PingFang SC",sans-serif}.state a{display:inline-block}@media(max-width:760px){.page{padding:15px}header{display:block}.actions{margin-top:12px}.overview{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}`}</style></main>;
}
