"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Property={id:number;name:string;address:string;customerId:number|null;customerName:string|null};
type Customer={id:number;name:string;email:string;customerNumber:string|null;status:string};
type Access={id:number;userName:string;email:string;propertyId:number;role:string;status:string;revokedAt:string|null};

export default function Page(){
  const[properties,setProperties]=useState<Property[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[access,setAccess]=useState<Access[]>([]),[url,setUrl]=useState(""),[message,setMessage]=useState(""),[linkCustomerId,setLinkCustomerId]=useState(0),[form,setForm]=useState({propertyId:0,email:"",phone:"",displayName:"",accessRole:"household"});
  const selected=useMemo(()=>properties.find(property=>property.id===form.propertyId),[properties,form.propertyId]);
  const load=async()=>{const response=await fetch("/api/v4/customer-access",{cache:"no-store"}),data=await response.json();if(!response.ok){setMessage(data.error);return}setProperties(data.properties||[]);setCustomers(data.customers||[]);setAccess(data.access||[]);setForm(current=>({...current,propertyId:current.propertyId||data.properties?.[0]?.id||0}));setLinkCustomerId(current=>current||data.customers?.[0]?.id||0)};
  useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[]);
  const linkCustomer=async()=>{if(!form.propertyId||!linkCustomerId)return;const response=await fetch("/api/v4/customer-access",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId:form.propertyId,customerId:linkCustomerId})}),data=await response.json();setMessage(response.ok?"Property linked to existing Customer. You may now create the invitation.":data.error||"Unable to link Customer");if(response.ok)await load()};
  const invite=async(event:FormEvent)=>{event.preventDefault();const response=await fetch("/api/v4/customer-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),data=await response.json();if(!response.ok){setMessage(data.error);return}setUrl(`${location.origin}${data.invitation.url}`);setMessage("Invitation created. Copy the secure link; it expires in 7 days.")};
  const revoke=async(id:number)=>{if(!confirm("Revoke access and all active sessions?"))return;const response=await fetch("/api/v4/customer-access",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessId:id})});setMessage(response.ok?"Access revoked":"Unable to revoke");await load()};
  const removeTestProperty=async()=>{if(!selected||selected.customerId||form.displayName!==selected.name){setMessage(`请先在 Name 输入完整 Property 名称：${selected?.name||""}`);return}const response=await fetch("/api/v4/customer-access",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId:selected.id,confirmation:form.displayName})}),data=await response.json();setMessage(response.ok?`已清理测试 Property：${data.deleted.name}（${data.deleted.rooms} Rooms，${data.deleted.windows} Windows）`:data.error||"Unable to delete test Property");if(response.ok){setForm(current=>({...current,propertyId:0,displayName:""}));await load()}};
  return <main className="page"><header><div><small>SPRINT 9 · CUSTOMER ACCESS #148</small><h1>客户门户授权 / Customer Access</h1><p>Owner 为家庭联系人授予指定 Property 权限；撤销后立即终止该账号的活动会话。</p></div><Link href="/hub">Hub</Link></header><form className="card form" onSubmit={invite}><h2>Invite customer / household contact</h2><label>Property<select value={form.propertyId} onChange={event=>setForm({...form,propertyId:+event.target.value})}>{properties.map(property=><option key={property.id} value={property.id}>{property.name} · {property.customerName||"No linked customer"}</option>)}</select></label>{selected&&!selected.customerId&&<section className="link-customer"><h3>先关联现有 Customer / Link existing Customer first</h3>{customers.length?<><select aria-label="Existing Customer" value={linkCustomerId} onChange={event=>setLinkCustomerId(+event.target.value)}>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.customerNumber||`#${customer.id}`} · {customer.name||customer.email} · {customer.status}</option>)}</select><button type="button" onClick={()=>void linkCustomer()}>Link Customer to this Property</button></>:<p>暂无可关联客户。<Link href="/customers">先建立 Customer</Link></p>}<button className="danger" type="button" onClick={()=>void removeTestProperty()}>清理未关联的测试 Property</button></section>}<label>Name<input required value={form.displayName} onChange={event=>setForm({...form,displayName:event.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Phone<input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></label><label>Access role<select value={form.accessRole} onChange={event=>setForm({...form,accessRole:event.target.value})}><option value="primary">Primary</option><option value="co_owner">Co-owner</option><option value="household">Household</option></select></label><button disabled={!selected?.customerId}>Generate secure invitation</button>{url&&<div className="link"><code>{url}</code><button type="button" onClick={()=>void navigator.clipboard.writeText(url)}>Copy</button></div>}</form>{message&&<p className="message">{message}</p>}<section className="card"><h2>Active and revoked access</h2>{access.map(item=><article key={item.id}><div><b>{item.userName}</b><small>{item.email}</small></div><span>Property #{item.propertyId}</span><span>{item.role}</span><strong>{item.status}</strong>{item.status==="active"&&<button onClick={()=>void revoke(item.id)}>Revoke</button>}</article>)}</section><style jsx>{styles}</style></main>;
}

const styles=`.page{min-height:100vh;background:#f3f0e9;color:#20372f;padding:20px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.message{max-width:1150px;margin:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:24px;display:flex;justify-content:space-between}a,button{border:0;border-radius:9px;padding:10px 12px;background:#ddb158;color:#173f35;text-decoration:none;font-weight:800}button.danger{grid-column:1/-1;background:#a5392f;color:white}.card{margin-top:14px;background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px}.form{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.form h2,.form .link,.link-customer{grid-column:1/-1}.form label{display:grid;gap:6px;font-weight:700}.form input,.form select,.link-customer select{padding:10px;border:1px solid #bdc9c3;border-radius:8px}.form>button{background:#1e6650;color:white}.form>button:disabled{opacity:.45}.link-customer{background:#fff4d9;border:1px solid #e2c989;border-radius:12px;padding:14px;display:grid;grid-template-columns:1fr auto;gap:9px}.link-customer h3,.link-customer p{grid-column:1/-1;margin:0}.link{display:flex;gap:8px}.link code{flex:1;word-break:break-all;background:#f0f3f0;padding:10px}.message{margin-top:12px;padding:10px;background:#eaf2ed}article{display:grid;grid-template-columns:1fr repeat(3,130px) auto;gap:12px;align-items:center;border-top:1px solid #e2e4df;padding:12px 0}article div{display:grid}article small{color:#68766f}@media(max-width:700px){.page{padding:10px}.form{grid-template-columns:1fr}.form h2,.form .link,.link-customer{grid-column:1}.link-customer{grid-template-columns:1fr}.link,header{flex-direction:column}article{grid-template-columns:1fr 1fr}}`;
