"use client";

import { useEffect,useMemo,useState } from "react";
import { detectWorkbookType,findDuplicates,NormalizedImportRow,parseCommerceRows,parseWholesaleWorkbook } from "@/lib/excel-import-rules";

type SheetCell=string|number|boolean|null;
type XlsxApi={read:(data:ArrayBuffer)=>{SheetNames:string[];Sheets:Record<string,unknown>};utils:{sheet_to_json:(sheet:unknown,options:{header:number;defval:null;raw:boolean})=>SheetCell[][]}};
declare global{interface Window{XLSX?:XlsxApi}}
function loadXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise<XlsxApi>((resolve,reject)=>{const script=document.createElement("script");script.src="https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js";script.onload=()=>window.XLSX?resolve(window.XLSX):reject(new Error("XLSX 加载失败"));script.onerror=()=>reject(new Error("XLSX 加载失败"));document.head.appendChild(script);});}
async function sha256(buffer:ArrayBuffer){const digest=await crypto.subtle.digest("SHA-256",buffer);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");}

export default function DataImportPage(){
 const[lang,setLang]=useState<"zh"|"en">("zh");const[rows,setRows]=useState<NormalizedImportRow[]>([]);const[fileName,setFileName]=useState("");const[fileHash,setFileHash]=useState("");const[workbookType,setWorkbookType]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[confirmed,setConfirmed]=useState(false);const t=(zh:string,en:string)=>lang==="zh"?zh:en;
 useEffect(()=>{loadXlsx().catch(()=>setMessage("Excel 解析组件加载失败"));},[]);
 const summary=useMemo(()=>({usd:rows.filter(r=>r.currency==="USD").reduce((s,r)=>s+(r.amount||0),0),rmb:rows.filter(r=>r.currency==="RMB").reduce((s,r)=>s+(r.amount||0),0),warnings:rows.reduce((s,r)=>s+r.warnings.length,0),orders:rows.filter(r=>r.recordType==="order").length,expenses:rows.filter(r=>r.recordType==="expense").length,payments:rows.filter(r=>r.recordType==="payment").length}),[rows]);
 async function handleFile(file?:File){if(!file)return;setBusy(true);setMessage("");setRows([]);setConfirmed(false);setFileName(file.name);try{const buffer=await file.arrayBuffer();setFileHash(await sha256(buffer));const XLSX=await loadXlsx();const workbook=XLSX.read(buffer);const type=detectWorkbookType(workbook.SheetNames);setWorkbookType(type);let parsed:NormalizedImportRow[]=[];if(type==="jin-commerce"){const name="Commerce订单汇总";parsed=parseCommerceRows(file.name,name,XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:null,raw:true}));}else if(type==="wholesale-sales"){const sheets:Record<string,unknown[][]>={};for(const name of workbook.SheetNames)sheets[name]=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:null,raw:true});parsed=parseWholesaleWorkbook(file.name,sheets);}else setMessage(t("暂时无法识别此表格。","Workbook format is not recognized."));setRows(findDuplicates(parsed));}catch(error){setMessage(error instanceof Error?error.message:t("读取失败","Read failed"));}finally{setBusy(false);}}
 async function confirmImport(){if(!rows.length||!fileHash||confirmed)return;setBusy(true);setMessage("");try{const response=await fetch("/api/v4/imports/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName,fileHash,workbookType,rows})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||t("确认失败","Confirmation failed"));setConfirmed(true);setMessage(t(`导入批次 #${data.batchId} 已保存到安全暂存区。`,`Import batch #${data.batchId} was saved to staging.`));}catch(error){setMessage(error instanceof Error?error.message:t("确认失败","Confirmation failed"));}finally{setBusy(false);}}
 return <main className="import-page"><header><div><small>BRAUN SMART PORTAL</small><h1>{t("真实数据导入中心","Real Data Import Center")}</h1><p>{t("先预览并核对币种、来源和重复项，再保存到安全暂存区。","Preview currency, sources and duplicates before saving to staging.")}</p></div><div className="actions"><a href="/data-import/history">{t("导入历史","Import History")}</a><button onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"English":"中文"}</button></div></header>
 <section className="upload-card"><label><strong>{t("选择 Excel 文件","Choose Excel file")}</strong><span>{t("支持批发销售和 Jin 汇总","Supports Wholesale Sales and Jin Summary")}</span><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>handleFile(e.target.files?.[0])}/></label>{message&&<div className="message">{message}</div>}</section>
 {fileName&&<section className="summary-grid"><div><span>{t("文件","File")}</span><strong>{fileName}</strong></div><div><span>{t("类型","Type")}</span><strong>{workbookType}</strong></div><div><span>USD</span><strong>${summary.usd.toFixed(2)}</strong></div><div><span>RMB</span><strong>¥{summary.rmb.toFixed(2)}</strong></div><div><span>{t("订单/支出/付款","Orders/Expenses/Payments")}</span><strong>{summary.orders}/{summary.expenses}/{summary.payments}</strong></div><div><span>{t("警告","Warnings")}</span><strong>{summary.warnings}</strong></div></section>}
 {rows.length>0&&<section className="preview-card"><div className="preview-title"><div><h2>{t("导入预览","Import Preview")}</h2><p>{rows.length} {t("条标准化记录","normalized records")} · SHA-256 {fileHash.slice(0,12)}…</p></div><button disabled={busy||confirmed} onClick={confirmImport}>{confirmed?t("已确认保存","Saved"):busy?t("处理中…","Processing…"):t("确认导入到暂存区","Confirm to Staging")}</button></div><div className="notice">{t("本步骤不会修改正式订单、收款或支出。含币种警告的记录必须在生成正式业务数据前人工核对。","This step does not modify live orders, payments or expenses. Currency warnings must be reviewed before committing business records.")}</div><div className="table-wrap"><table><thead><tr><th>#</th><th>{t("类型","Type")}</th><th>{t("订单号","Order")}</th><th>{t("客户/对象","Customer/Payee")}</th><th>{t("项目/产品","Project/Product")}</th><th>{t("金额","Amount")}</th><th>{t("状态","Status")}</th><th>{t("来源","Source")}</th><th>{t("检查","Checks")}</th></tr></thead><tbody>{rows.slice(0,500).map((row,index)=><tr key={`${row.source.sheetName}-${row.source.rowNumber}-${index}`}><td>{index+1}</td><td>{row.recordType}</td><td>{row.orderNumber||"—"}</td><td>{row.customer||"—"}</td><td>{row.project||row.product||"—"}<small>{row.notes}</small></td><td className={row.currency==="RMB"?"rmb":"usd"}>{row.amount===null?"—":`${row.currency==="RMB"?"¥":"$"}${row.amount.toFixed(2)}`}</td><td>{row.status||"—"}</td><td>{row.source.sheetName} #{row.source.rowNumber}</td><td>{row.warnings.length?row.warnings.map(w=><span className="warning" key={w}>{w}</span>):<span className="ok">OK</span>}</td></tr>)}</tbody></table></div></section>}
 <style jsx>{`.import-page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:32px;font-family:Arial,"PingFang SC",sans-serif}header{display:flex;justify-content:space-between;gap:20px;max-width:1450px;margin:auto}.actions{display:flex;gap:10px;align-items:flex-start}small{display:block;color:#6d7d77;margin-top:5px}h1{font-size:34px;margin:5px 0}p{color:#60716b}button,a{border:0;border-radius:10px;padding:11px 16px;background:#1f5b49;color:white;font-weight:700;text-decoration:none}button:disabled{background:#b6beb9}.upload-card,.preview-card{max-width:1450px;margin:22px auto;background:white;border:1px solid #dedbd3;border-radius:18px;padding:22px}.upload-card label{display:grid;gap:7px}input{margin-top:12px;padding:14px;border:1px dashed #9baaa4;border-radius:12px}.message,.notice{margin-top:14px;padding:12px;background:#fff3d8;border-radius:10px}.summary-grid{max-width:1450px;margin:0 auto;display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.summary-grid div{background:white;padding:16px;border-radius:14px;border:1px solid #dedbd3}.summary-grid span{display:block;color:#687871;font-size:12px}.summary-grid strong{display:block;margin-top:6px}.preview-title{display:flex;justify-content:space-between;align-items:center;gap:16px}.table-wrap{overflow:auto;margin-top:14px}table{border-collapse:collapse;width:100%;min-width:1200px}th,td{border-bottom:1px solid #e7e4dd;padding:11px;text-align:left;vertical-align:top;font-size:13px}th{position:sticky;top:0;background:#edf3f0}.usd{color:#155d47;font-weight:700}.rmb{color:#9a4e16;font-weight:700}.warning{display:block;color:#a33d28}.ok{color:#27815e}@media(max-width:850px){.import-page{padding:16px}.summary-grid{grid-template-columns:1fr 1fr}header{display:block}.actions{margin-top:12px}.preview-title{display:block}.preview-title button{margin-top:10px}}`}</style></main>;
}
