import { desc, eq, max } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/db";
import { measureProperties, measureRooms, measureWindows, roomSketchVersions } from "@/db/schema";
import { getCurrentAppUser, writeAuditLog } from "@/lib/v4-auth";

type SketchObject={id:string;type:string;label:string;x:number;y:number;width:number;height:number;rotation:number;notes:string;windowId:number|null};
const types=new Set(["wall","door","sliding_door","window","stairs","fireplace","tv","furniture","outlet","switch","beam","obstacle"]);
const clean=(value:unknown,max=500)=>String(value??"").replace(/\s+/g," ").trim().slice(0,max);
const finite=(value:unknown,min:number,max:number)=>{const n=Number(value);return Number.isFinite(n)&&n>=min&&n<=max?n:null};
async function context(roomId:number){const user=await getCurrentAppUser();if(!user)return {error:NextResponse.json({error:"Authentication required"},{status:401})};if(!["owner","sales","installer"].includes(user.role))return {error:NextResponse.json({error:"Permission denied"},{status:403})};const db=await getDb(),rows=await db.select({room:measureRooms,property:measureProperties}).from(measureRooms).innerJoin(measureProperties,eq(measureProperties.id,measureRooms.propertyId)).where(eq(measureRooms.id,roomId)).limit(1),row=rows[0];if(!row||(user.role==="sales"&&row.property.createdBy!==user.id))return {error:NextResponse.json({error:"Room not found"},{status:404})};return {user,db,row}}

export async function GET(_request:NextRequest,{params}:{params:Promise<{roomId:string}>}){const roomId=Number((await params).roomId),ctx=await context(roomId);if("error" in ctx)return ctx.error;const versions=await ctx.db.select().from(roomSketchVersions).where(eq(roomSketchVersions.roomId,roomId)).orderBy(desc(roomSketchVersions.version)).limit(30),windows=await ctx.db.select({id:measureWindows.id,code:measureWindows.code}).from(measureWindows).where(eq(measureWindows.roomId,roomId));return NextResponse.json({room:ctx.row.room,property:ctx.row.property,windows,versions:versions.map(item=>({...item,objects:JSON.parse(item.objectsJson)})),capabilities:{edit:ctx.user.role!=="installer"}})}

export async function POST(request:NextRequest,{params}:{params:Promise<{roomId:string}>}){const roomId=Number((await params).roomId),ctx=await context(roomId);if("error" in ctx)return ctx.error;if(ctx.user.role==="installer")return NextResponse.json({error:"Read only"},{status:403});let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request"},{status:400})}const raw=Array.isArray(body.objects)?body.objects:[];if(raw.length>250)return NextResponse.json({error:"Too many sketch objects"},{status:400});const windowIds=new Set((await ctx.db.select({id:measureWindows.id}).from(measureWindows).where(eq(measureWindows.roomId,roomId))).map(item=>item.id));const objects:SketchObject[]=[];for(const rawItem of raw){const item=rawItem as Record<string,unknown>,type=clean(item.type,30),x=finite(item.x,0,100),y=finite(item.y,0,100),width=finite(item.width,1,100),height=finite(item.height,1,100),rotation=finite(item.rotation,0,359),windowId=item.windowId===null||item.windowId===undefined?null:Number(item.windowId);if(!types.has(type)||x===null||y===null||width===null||height===null||rotation===null||(type==="window"&&(!Number.isInteger(windowId)||!windowIds.has(windowId!))))return NextResponse.json({error:"Invalid sketch object"},{status:400});objects.push({id:clean(item.id,80)||crypto.randomUUID(),type,label:clean(item.label,100),x,y,width,height,rotation,notes:clean(item.notes,1000),windowId})}const latest=await ctx.db.select({version:max(roomSketchVersions.version)}).from(roomSketchVersions).where(eq(roomSketchVersions.roomId,roomId)),version=Number(latest[0]?.version||0)+1,created=await ctx.db.insert(roomSketchVersions).values({roomId,version,objectsJson:JSON.stringify(objects),scaleLabel:clean(body.scaleLabel,100)||"not_to_scale",internalNotes:clean(body.internalNotes,2000),createdBy:ctx.user.id}).returning();await writeAuditLog({userId:ctx.user.id,action:"room_sketch_version_created",entityType:"room_sketch_version",entityId:String(created[0].id),details:{roomId,version,objectCount:objects.length}});return NextResponse.json({sketch:{...created[0],objects}},{status:201})}
