"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Customer={id:number;customerNumber:string|null;customerType:string;displayName:string;companyName:string;contactName:string;email:string;phone:string;status:string;archivedAt:string|null};
type Duplicate={id:number;customerNumber:string|null;displayName:string;companyName:string;contactName:string;email:string;phone:string};
const emptyForm={displayName:"",companyName:"",contactName:"",email:"",phone:"",customerType:"retail"};

export default function CustomersPage(){
  const [customers,setCustomers]=useState<Customer[]>([]),[query,setQuery]=useState(""),[submitted,setSubmitted]=useState(""),[type,setType]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [canCreate,setCanCreate]=useState(false),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(emptyForm),[duplicates,setDuplicates]=useState<Duplicate[]>([]),[createError,setCreateError]=useState("");
  const pageSize=25;
  const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(submitted)params.set("q",submitted);if(type)params.set("type",type);if(status)params.set("status",status);const response=await fetch(`/api/v4/customers?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load customers");setCustomers(data.customers||[]);setTotal(Number(data.total)||0);setCanCreate(Boolean(data.capabilities?.create))}catch(reason){setCustomers([]);setError(reason instanceof Error?reason.message:"Unable to load customers")}finally{setLoading(false)}},[page,status,submitted,type]);
  // Synchronize filters with the protected Customer 360 API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const search=(event:FormEvent)=>{event.preventDefault();setPage(1);setSubmitted(query.trim())};
  const create=async(event:FormEvent,confirmCreate=false)=>{event.preventDefault();if(saving)return;setSaving(true);setCreateError("");try{const response=await fetch("/api/v4/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,confirmCreate})});const data=await response.json();if(response.status===409&&data.requiresConfirmation){setDuplicates(data.duplicateCandidates||[]);return}if(!response.ok)throw new Error(data.error||"Unable to create customer");location.href=`/customers/${data.customer.id}`}catch(reason){setCreateError(reason instanceof Error?reason.message:"Unable to create customer")}finally{setSaving(false)}};
  return <main className="page"><header><div><small>BRN-003 · CUSTOMER 360</small><h1>客户中心 <span>Customers</span></h1><p>只显示当前账号有权访问的真实客户主档、联系人、地址和订单。</p></div><div className="actions"><Link href="/hub">返回门户</Link><Link href="/orders">订单中心</Link><button onClick={()=>void load()}>刷新</button>{canCreate&&<button onClick={()=>{setCreating(true);setDuplicates([])}}>＋ 新建客户</button>}</div></header>
    <form className="filters" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="编号、姓名、公司、电话或邮箱"/><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">全部类型</option>{["retail","wholesale","designer","contractor","commercial","other"].map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">全部状态</option><option>active</option><option>pending</option><option>archived</option></select><button>搜索</button></form>
    {creating&&<form className="create" onSubmit={event=>void create(event)}><div className="create-head"><div><h2>新建客户 <span>Create Customer</span></h2><p>系统会先检查电话和邮箱重复项；客户编号由服务端生成。</p></div><button type="button" onClick={()=>setCreating(false)}>关闭</button></div><div className="form-grid"><label>显示名称<input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>客户类型<select value={form.customerType} onChange={e=>setForm({...form,customerType:e.target.value})}>{["retail","wholesale","designer","contractor","commercial","other"].map(value=><option key={value}>{value}</option>)}</select></label><label>公司<input value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})}/></label><label>主要联系人<input value={form.contactName} onChange={e=>setForm({...form,contactName:e.target.value})}/></label><label>邮箱<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>电话<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div>{duplicates.length>0&&<div className="warning"><b>发现潜在重复客户，请先核对：</b>{duplicates.map(item=><Link key={item.id} href={`/customers/${item.id}`}>{item.customerNumber||`#${item.id}`} · {item.displayName||item.companyName||item.contactName} · {item.email||item.phone}</Link>)}<button type="button" disabled={saving} onClick={event=>void create(event,true)}>确认仍创建新客户</button></div>}{createError&&<div className="error">{createError}</div>}<button disabled={saving}>{saving?"正在检查…":"检查并创建"}</button></form>}
    {error&&<div className="error outer">{error}</div>}<section className="card"><div className="summary"><b>{total}</b> 个当前账号可访问的客户</div><div className="table"><table><thead><tr><th>客户编号</th><th>客户</th><th>类型</th><th>联系方式</th><th>状态</th></tr></thead><tbody>{customers.map(customer=><tr key={customer.id}><td><Link className="customer-link" href={`/customers/${customer.id}`}>{customer.customerNumber||`#${customer.id}`}</Link></td><td><b>{customer.displayName||customer.companyName||customer.contactName}</b><small>{customer.companyName&&customer.companyName!==customer.displayName?customer.companyName:"—"}</small></td><td>{customer.customerType}</td><td>{customer.phone||"—"}<small>{customer.email}</small></td><td><span className="pill">{customer.archivedAt?"archived":customer.status}</span></td></tr>)}</tbody></table>{loading&&<div className="empty">正在读取真实客户…</div>}{!loading&&!customers.length&&<div className="empty">没有符合条件的客户</div>}</div><div className="pagination"><button disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)}>上一页</button><span>第 {page} 页</span><button disabled={page*pageSize>=total||loading} onClick={()=>setPage(value=>value+1)}>下一页</button></div></section>
    <style jsx>{styles}</style></main>;
}

const styles=`.page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:30px;font-family:Arial,"PingFang SC",sans-serif}header,.filters,.create,.card,.outer{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;gap:20px}h1{font-size:36px;margin:7px 0}h1 span,h2 span{font-weight:400;color:#687871}small{display:block;color:#6b7a74;margin-top:5px}.actions{display:flex;gap:9px;align-items:flex-start;flex-wrap:wrap}a,button{border:0;border-radius:9px;padding:10px 14px;background:#1f5b49;color:white;text-decoration:none;font-weight:800}.filters{display:grid;grid-template-columns:1fr 180px 180px auto;gap:10px;margin-top:22px}.filters input,.filters select,.form-grid input,.form-grid select{box-sizing:border-box;width:100%;border:1px solid #cfd7d2;border-radius:10px;padding:12px;background:white}.create,.card{background:white;border:1px solid #dedbd3;border-radius:18px;padding:20px;margin-top:16px}.create-head{display:flex;justify-content:space-between;gap:15px}.create-head h2{margin:0}.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.form-grid label{display:grid;gap:6px;font-size:13px;font-weight:700}.warning,.error{display:grid;gap:8px;background:#fff7df;color:#735821;padding:13px;border-radius:10px;margin:12px 0}.warning a{background:none;color:#174f3e;padding:2px}.error{background:#fff0ec;color:#95392e}.summary{margin-bottom:12px}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:900px}th,td{padding:13px;border-bottom:1px solid #e8e5de;text-align:left;font-size:13px}.customer-link{background:none;color:#174f3e;padding:0}.pill{background:#e8f0eb;border-radius:999px;padding:6px 9px}.empty{text-align:center;padding:35px;color:#74817b}.pagination{display:flex;justify-content:center;align-items:center;gap:13px;margin-top:17px}button:disabled{opacity:.45}@media(max-width:760px){.page{padding:15px}header{display:block}.actions{margin-top:12px}.filters,.form-grid{grid-template-columns:1fr}.card,.create{padding:13px}}`;
