"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { formatSixteenths } from "@/lib/measurement-sixteenths";

type Value={fieldKey:string;wholeInches:number;fractionSixteenths:number;totalSixteenths:number};
type Version={id:number;version:number;productType:string;mountType:string;controlSide:string;status:string;obstacleNotes:string;notes:string;createdAt:string;values:Value[]};
type WindowItem={id:number;propertyId:number;roomId:number;code:string;versions:Version[]};
type Room={id:number;propertyId:number;name:string;windows:WindowItem[]};
type Property={id:number;name:string;address:string;rooms:Room[]};
const fieldLabels:Record<string,[string,string]>={width_left:["宽度左","Width left"],width_center:["宽度中","Width center"],width_right:["宽度右","Width right"],height_left:["高度左","Height left"],height_center:["高度中","Height center"],height_right:["高度右","Height right"],depth:["窗框深度","Depth"],ceiling_height:["层高","Ceiling height"],sill_height:["窗台高度","Sill height"],floor_clearance:["离地间隙","Floor clearance"],return_left:["左 Return","Left return"],return_right:["右 Return","Right return"],overlap_left:["左 Overlap","Left overlap"],overlap_right:["右 Overlap","Right overlap"],stack_back_left:["左 Stack Back","Left stack back"],stack_back_right:["右 Stack Back","Right stack back"],handle_projection:["把手突出","Handle projection"]};
const keys=Object.keys(fieldLabels),initial=Object.fromEntries(keys.map(key=>[key,{whole:"",fraction:""}])) as Record<string,{whole:string;fraction:string}>;
const products=["drapery","roman","roller","zebra","honeycomb","shutter","blind","track_rod","cornice_valance","motorized"];

export default function MeasurePage(){
 const [lang,setLang]=useState<"zh-CN"|"en">("zh-CN"),[properties,setProperties]=useState<Property[]>([]),[propertyId,setPropertyId]=useState(0),[roomId,setRoomId]=useState(0),[windowId,setWindowId]=useState(0),[dimensions,setDimensions]=useState(initial),[productType,setProductType]=useState("roller"),[mountType,setMountType]=useState("inside"),[controlSide,setControlSide]=useState("right"),[notes,setNotes]=useState(""),[obstacles,setObstacles]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const t=(zh:string,en:string)=>lang==="zh-CN"?zh:en;
 const load=async()=>{const response=await fetch("/api/v4/measure/workspace",{cache:"no-store"});if(response.status===401){location.href="/login";return}const data=await response.json();if(!response.ok){setMessage(data.error);return}setProperties(data.properties||[])};
 // Initial server-backed workspace hydration; later refreshes follow explicit saves.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const selectedPropertyId=properties.some(item=>item.id===propertyId)?propertyId:properties[0]?.id||0;
 const property=properties.find(item=>item.id===selectedPropertyId),rooms=property?.rooms||[];
 const selectedRoomId=rooms.some(item=>item.id===roomId)?roomId:rooms[0]?.id||0;
 const room=rooms.find(item=>item.id===selectedRoomId),windows=room?.windows||[];
 const selectedWindowId=windows.some(item=>item.id===windowId)?windowId:windows[0]?.id||0;
 const window=windows.find(item=>item.id===selectedWindowId),latest=window?.versions?.[0];
 const canSave=selectedWindowId>0&&keys.some(key=>key.startsWith("width_")&&dimensions[key].whole!=="")&&keys.some(key=>key.startsWith("height_")&&dimensions[key].whole!=="");
 const action=async(body:Record<string,unknown>)=>{setBusy(true);setMessage("");try{const response=await fetch("/api/v4/measure/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error);await load();return data}catch(error){setMessage(error instanceof Error?error.message:t("保存失败","Save failed"))}finally{setBusy(false)}};
 const promptCreate=async(kind:"property"|"room"|"window")=>{const label=kind==="property"?t("项目名称","Property name"):kind==="room"?t("房间名称","Room name"):t("Window 编号，例如 LR-1","Window code, e.g. LR-1"),name=prompt(label);if(!name)return;if(kind==="property"){const address=prompt(t("地址（可留空）","Address (optional)"))||"",data=await action({action:"create_property",name,address});if(data?.property)setPropertyId(data.property.id)}else if(kind==="room"){if(!selectedPropertyId)return;const data=await action({action:"create_room",propertyId:selectedPropertyId,name});if(data?.room)setRoomId(data.room.id)}else{if(!selectedPropertyId||!selectedRoomId)return;const data=await action({action:"create_window",propertyId:selectedPropertyId,roomId:selectedRoomId,code:name});if(data?.window)setWindowId(data.window.id)}};
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!canSave)return;const values=keys.filter(key=>dimensions[key].whole!=="").map(fieldKey=>({fieldKey,wholeInches:Number(dimensions[fieldKey].whole),fractionSixteenths:Number(dimensions[fieldKey].fraction||0)}));const data=await action({action:"save_measurement",propertyId:selectedPropertyId,windowId:selectedWindowId,productType,mountType,controlSide,notes,obstacleNotes:obstacles,values});if(data?.measurement){setMessage(t(`已保存版本 V${data.measurement.version}`,`Saved version V${data.measurement.version}`));setDimensions(initial);setNotes("");setObstacles("")}};
 return <main className="page"><header><div><small>SPRINT 8 · SMART MEASURE #139</small><h1>{t("智能测量中心","Smart Measure")}</h1><p>{t("Property → Room → Window 永久编号；每次保存建立新版本，统一使用 1/16 英寸。","Permanent Property → Room → Window identity. Every save creates a version in canonical 1/16 inch units.")}</p></div><nav><button type="button" onClick={()=>setLang(lang==="zh-CN"?"en":"zh-CN")}>{lang==="zh-CN"?"English":"中文"}</button><Link href="/hub">{t("返回入口","Back to hub")}</Link></nav></header>
 <section className="card hierarchy"><div><label>{t("项目 / Property","Property")}</label><div className="row"><select value={selectedPropertyId} onChange={e=>{setPropertyId(Number(e.target.value));setRoomId(0);setWindowId(0)}}><option value={0}>{t("选择项目","Select property")}</option>{properties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={()=>void promptCreate("property")}>＋</button></div></div><div><label>{t("房间","Room")}</label><div className="row"><select value={selectedRoomId} onChange={e=>{setRoomId(Number(e.target.value));setWindowId(0)}}><option value={0}>{t("选择房间","Select room")}</option>{rooms.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!selectedPropertyId} onClick={()=>void promptCreate("room")}>＋</button></div></div><div><label>Window</label><div className="row"><select value={selectedWindowId} onChange={e=>setWindowId(Number(e.target.value))}><option value={0}>{t("选择 Window","Select window")}</option>{windows.map(item=><option key={item.id} value={item.id}>{item.code}</option>)}</select><button disabled={!selectedRoomId} onClick={()=>void promptCreate("window")}>＋</button></div></div></section>
 {window&&<div className="layout"><form className="card" onSubmit={submit}><div className="title"><div><small>{property?.name} / {room?.name}</small><h2>{window.code}</h2></div><span>{t("新测量版本","New measurement version")}</span></div><div className="settings"><label>{t("产品类型","Product type")}<select value={productType} onChange={e=>setProductType(e.target.value)}>{products.map(item=><option key={item}>{item.replaceAll("_"," / ")}</option>)}</select></label><label>{t("安装方式","Mount type")}<select value={mountType} onChange={e=>setMountType(e.target.value)}><option value="inside">Inside</option><option value="outside">Outside</option><option value="ceiling">Ceiling</option></select></label><label>{t("控制方向","Control side")}<select value={controlSide} onChange={e=>setControlSide(e.target.value)}><option value="left">Left</option><option value="right">Right</option><option value="center">Center</option><option value="unspecified">N/A</option></select></label></div><h3>{t("三点尺寸与现场尺寸","Three-point & site dimensions")}</h3><div className="dimensions">{keys.map(key=><label key={key}><span>{lang==="zh-CN"?fieldLabels[key][0]:fieldLabels[key][1]}</span><div className="dimension"><input min="0" step="1" inputMode="numeric" placeholder="0" value={dimensions[key].whole} onChange={e=>setDimensions({...dimensions,[key]:{...dimensions[key],whole:e.target.value}})}/><b>in</b><select aria-label={`${fieldLabels[key][1]} fraction`} value={dimensions[key].fraction} onChange={e=>setDimensions({...dimensions,[key]:{...dimensions[key],fraction:e.target.value}})}><option value="">—</option>{Array.from({length:15},(_,index)=><option key={index+1} value={index+1}>{index+1}/16</option>)}</select></div></label>)}</div><div className="notes"><label>{t("障碍物与把手、电源说明","Obstacles, handles & power")}<textarea value={obstacles} onChange={e=>setObstacles(e.target.value)}/></label><label>{t("现场备注","Site notes")}<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{message&&<div role="status" className="message">{message}</div>}<button className="save" disabled={busy||!canSave}>{busy?t("保存中…","Saving…"):t("保存为新版本","Save as new version")}</button></form>
 <aside className="card"><h2>{t("版本历史","Version history")}</h2>{!latest&&<p className="muted">{t("还没有测量记录。","No measurements yet.")}</p>}{window.versions.map(version=><article key={version.id}><div><b>V{version.version} · {version.productType}</b><time>{new Date(version.createdAt).toLocaleString()}</time></div><p>{version.mountType} · {version.controlSide} · {version.status}</p><dl>{version.values.map(value=><div key={value.fieldKey}><dt>{lang==="zh-CN"?fieldLabels[value.fieldKey]?.[0]:fieldLabels[value.fieldKey]?.[1]}</dt><dd>{formatSixteenths(value.totalSixteenths)}</dd></div>)}</dl>{version.obstacleNotes&&<p>{version.obstacleNotes}</p>}{version.status==="draft"&&<button onClick={async()=>{const response=await fetch(`/api/v4/measure/measurement-versions/${version.id}/approve`,{method:"POST"});if(response.ok)await load();else setMessage((await response.json()).error)}}>{t("Owner 批准","Owner approve")}</button>}</article>)}</aside></div>}
 {!window&&<section className="card empty">{t("先建立或选择项目、房间和 Window。","Create or select a property, room and window first.")}</section>}<style jsx>{styles}</style></main>;
}
const styles=`.page{min-height:100vh;background:#f4f1ea;color:#23342d;padding:24px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.layout{max-width:1220px;margin-left:auto;margin-right:auto}header{background:#173f35;color:white;border-radius:20px;padding:26px;display:flex;justify-content:space-between;gap:18px;align-items:end}header small{color:#e1bd70;letter-spacing:1px}h1{margin:7px 0;font-size:32px}header p{margin:0;max-width:760px;color:#c9d8d2;line-height:1.55}nav{display:flex;gap:8px}button,a{border:0;border-radius:9px;padding:10px 13px;background:#d9ae5e;color:#173f35;text-decoration:none;font-weight:800;cursor:pointer}.card{box-sizing:border-box;background:white;border:1px solid #ded9ce;border-radius:18px;padding:20px}.hierarchy{margin-top:18px;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.hierarchy label,.settings label,.notes label{display:grid;gap:7px;font-size:12px;font-weight:800}.row{display:flex;gap:7px}.row select{flex:1}.row button{padding:9px 14px}.layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px;margin-top:18px;align-items:start}.title{display:flex;justify-content:space-between;align-items:start}.title h2{margin:5px 0}.title span{background:#e6f2ec;color:#17603f;padding:7px 10px;border-radius:999px;font-size:12px}.settings,.dimensions,.notes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.dimensions{grid-template-columns:repeat(2,1fr)}.dimensions label{display:grid;gap:6px;font-size:12px;font-weight:700}.dimension{display:grid;grid-template-columns:1fr auto 92px;align-items:center;border:1px solid #cbd5cf;border-radius:9px;overflow:hidden}.dimension input,.dimension select{border:0}.dimension b{color:#718078;font-size:12px}select,input,textarea{box-sizing:border-box;width:100%;border:1px solid #cbd5cf;border-radius:9px;padding:10px;background:white;font:inherit}textarea{min-height:84px;resize:vertical}.notes{grid-template-columns:1fr 1fr;margin-top:16px}.save{margin-top:16px;width:100%;background:#1f654f;color:white;padding:13px}.save:disabled,button:disabled{opacity:.45;cursor:not-allowed}.message{margin-top:14px;background:#f0f6f3;padding:11px;border-radius:9px}aside h2{margin-top:0}article{border-top:1px solid #e7e8e4;padding:14px 0}article>div{display:flex;justify-content:space-between;gap:8px}time,.muted{color:#77817c;font-size:12px}article p{font-size:12px;color:#66736d}dl{margin:8px 0;display:grid;grid-template-columns:1fr 1fr;gap:5px 10px}dl div{display:flex;justify-content:space-between;gap:8px;font-size:12px}dt{color:#65736c}dd{margin:0;font-weight:700}.empty{text-align:center;margin-top:18px;padding:48px;color:#68756f}@media(max-width:800px){.page{padding:12px}header{align-items:start;flex-direction:column;padding:20px}.hierarchy,.layout,.settings,.dimensions,.notes{grid-template-columns:1fr}.hierarchy{padding:15px}h1{font-size:27px}.card{padding:15px}}`;
