import { and, desc, eq, isNull } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/db";
import { appSessions, appUsers, customerInvitations, customerPropertyAccess, customers, measureProperties } from "@/db/schema";
import { getCurrentAppUser, sha256, writeAuditLog } from "@/lib/v4-auth";

const roles=new Set(["primary","co_owner","household"]);
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,"0")).join("");

export async function GET(){const user=await getCurrentAppUser();if(!user||user.role!=="owner")return NextResponse.json({error:"Owner only"},{status:403});const db=await getDb();return NextResponse.json({properties:await db.select({id:measureProperties.id,name:measureProperties.name,address:measureProperties.address,customerId:measureProperties.customerId,customerName:customers.displayName}).from(measureProperties).leftJoin(customers,eq(customers.id,measureProperties.customerId)).limit(500),customers:await db.select({id:customers.id,name:customers.displayName,email:customers.email,customerNumber:customers.customerNumber,status:customers.status}).from(customers).where(isNull(customers.archivedAt)).orderBy(customers.displayName).limit(1000),access:await db.select({id:customerPropertyAccess.id,userId:customerPropertyAccess.userId,userName:appUsers.displayName,email:appUsers.email,propertyId:customerPropertyAccess.propertyId,role:customerPropertyAccess.accessRole,status:customerPropertyAccess.status,grantedAt:customerPropertyAccess.grantedAt,revokedAt:customerPropertyAccess.revokedAt}).from(customerPropertyAccess).innerJoin(appUsers,eq(appUsers.id,customerPropertyAccess.userId)).orderBy(desc(customerPropertyAccess.grantedAt))})}

export async function POST(request:NextRequest){const user=await getCurrentAppUser();if(!user||user.role!=="owner")return NextResponse.json({error:"Owner only"},{status:403});let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request"},{status:400})}const propertyId=Number(body.propertyId),email=String(body.email||"").trim().toLowerCase(),phone=String(body.phone||"").trim(),displayName=String(body.displayName||"").trim().slice(0,120),accessRole=String(body.accessRole||"household");if(!propertyId||!/^\S+@\S+\.\S+$/.test(email)||!displayName||!roles.has(accessRole))return NextResponse.json({error:"Property, valid email, name and access role required"},{status:400});const db=await getDb(),property=(await db.select().from(measureProperties).where(eq(measureProperties.id,propertyId)).limit(1))[0];if(!property?.customerId)return NextResponse.json({error:"Property must be linked to a Customer"},{status:409});const raw=token(),created=(await db.insert(customerInvitations).values({customerId:property.customerId,propertyId,email,phone,displayName,accessRole,tokenHash:await sha256(raw),expiresAt:new Date(Date.now()+7*86400_000).toISOString(),invitedBy:user.id}).returning())[0];await writeAuditLog({userId:user.id,action:"customer_property_invited",entityType:"customer_invitation",entityId:String(created.id),details:{propertyId,email,accessRole}});return NextResponse.json({invitation:{id:created.id,expiresAt:created.expiresAt,url:`/accept-customer-invite?token=${raw}`}},{status:201})}

export async function PATCH(request:NextRequest){const user=await getCurrentAppUser();if(!user||user.role!=="owner")return NextResponse.json({error:"Owner only"},{status:403});const body=await request.json(),id=Number(body.accessId);if(!id)return NextResponse.json({error:"Access ID required"},{status:400});const db=await getDb(),row=(await db.select().from(customerPropertyAccess).where(and(eq(customerPropertyAccess.id,id),eq(customerPropertyAccess.status,"active"),isNull(customerPropertyAccess.revokedAt))).limit(1))[0];if(!row)return NextResponse.json({error:"Active grant not found"},{status:404});const now=new Date().toISOString();await db.update(customerPropertyAccess).set({status:"revoked",revokedBy:user.id,revokedAt:now}).where(eq(customerPropertyAccess.id,id));await db.update(appSessions).set({revokedAt:now}).where(and(eq(appSessions.userId,row.userId),isNull(appSessions.revokedAt)));await writeAuditLog({userId:user.id,action:"customer_property_access_revoked",entityType:"customer_property_access",entityId:String(id),details:{propertyId:row.propertyId,userId:row.userId}});return NextResponse.json({ok:true})}

export async function PUT(request:NextRequest){const user=await getCurrentAppUser();if(!user||user.role!=="owner")return NextResponse.json({error:"Owner only"},{status:403});const body=await request.json(),propertyId=Number(body.propertyId),customerId=Number(body.customerId);if(!propertyId||!customerId)return NextResponse.json({error:"Property and Customer required"},{status:400});const db=await getDb(),customer=(await db.select({id:customers.id}).from(customers).where(and(eq(customers.id,customerId),isNull(customers.archivedAt))).limit(1))[0];if(!customer)return NextResponse.json({error:"Active Customer not found"},{status:404});const linked=await db.update(measureProperties).set({customerId}).where(and(eq(measureProperties.id,propertyId),isNull(measureProperties.customerId))).returning({id:measureProperties.id});if(!linked.length)return NextResponse.json({error:"Property is already linked; reassignment requires a separate review"},{status:409});await writeAuditLog({userId:user.id,action:"measure_property_customer_linked",entityType:"measure_property",entityId:String(propertyId),details:{customerId}});return NextResponse.json({ok:true,propertyId,customerId})}
