"use client";

import Link from "next/link";
import { FormEvent, use, useCallback, useEffect, useState } from "react";

type Customer={id:number;customerNumber:string|null;customerType:string;displayName:string;legalName:string;companyName:string;contactName:string;email:string;phone:string;status:string;source:string;paymentTerms?:string;taxExemptStatus?:string;defaultDiscountValue?:number;preferredLanguage:string;createdAt:string;archivedAt:string|null};
type Contact={id:number;name:string;title:string;phoneRaw:string;emailRaw:string;preferredChannel:string;isPrimary:boolean;customerVisible:boolean};
type Address={id:number;addressType:string;label:string;line1:string;line2:string;city:string;state:string;postalCode:string;country:string;accessNotes:string;isDefault:boolean};
type Order={id:number;orderNumber:string;projectName:string;status:string;currency:string;grandTotal?:number;balanceDue?:number;updatedAt:string};

export default function CustomerWorkspace({params}:{params:Promise<{customerId:string}>}){
  const {customerId}=use(params),[customer,setCustomer]=useState<Customer|null>(null),[contacts,setContacts]=useState<Contact[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [contactOpen,setContactOpen]=useState(false),[addressOpen,setAddressOpen]=useState(false),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState("");
  const [contact,setContact]=useState({name:"",title:"",phone:"",email:"",preferredChannel:"email",isPrimary:false,customerVisible:true});
  const [address,setAddress]=useState({addressType:"shipping",label:"",line1:"",line2:"",city:"",state:"",postalCode:"",country:"US",accessNotes:"",isDefault:false});
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/v4/customers/${encodeURIComponent(customerId)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load customer");setCustomer(data.customer);setContacts(data.contacts||[]);setAddresses(data.addresses||[]);setOrders(data.orders||[])}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load customer")}finally{setLoading(false)}},[customerId]);
  // Initial route load synchronizes this workspace with the protected API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const submitContact=async(event:FormEvent)=>{event.preventDefault();await submit(`/api/v4/customers/${customerId}/contacts`,contact,()=>{setContactOpen(false);setContact({name:"",title:"",phone:"",email:"",preferredChannel:"email",isPrimary:false,customerVisible:true})})};
  const submitAddress=async(event:FormEvent)=>{event.preventDefault();await submit(`/api/v4/customers/${customerId}/addresses`,address,()=>{setAddressOpen(false);setAddress({...address,label:"",line1:"",line2:"",city:"",state:"",postalCode:"",accessNotes:"",isDefault:false})})};
  const submit=async(url:string,body:object,done:()=>void)=>{if(saving)return;setSaving(true);setFeedback("");try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to save");done();setFeedback("保存成功");await load()}catch(reason){setFeedback(reason instanceof Error?reason.message:"Unable to save")}finally{setSaving(false)}};
  if(loading)return <main className="state">正在读取 Customer 360…</main>;
  if(error||!customer)return <main className="state"><p>{error||"Customer not found"}</p><Link href="/customers">返回客户中心</Link></main>;
  const usd=orders.filter(order=>order.currency==="USD").reduce((sum,order)=>sum+(order.balanceDue||0),0),rmb=orders.filter(order=>order.currency==="RMB").reduce((sum,order)=>sum+(order.balanceDue||0),0);
  return <main className="page"><header><div><small>CUSTOMER 360 / 客户全景</small><h1>{customer.displayName||customer.companyName||customer.contactName}</h1><p>{customer.customerNumber||`#${customer.id}`} · {customer.customerType} · {customer.status}</p></div><div className="actions"><Link href="/customers">← 客户列表</Link><Link href="/orders">订单中心</Link><button onClick={()=>void load()}>刷新</button></div></header>
    {feedback&&<div className="feedback">{feedback}</div>}<section className="kpis"><article><span>订单数量</span><b>{orders.length}</b></article><article><span>USD 欠款</span><b>USD {usd.toFixed(2)}</b></article><article><span>RMB 欠款</span><b>RMB {rmb.toFixed(2)}</b></article><article><span>联系人 / 地址</span><b>{contacts.length} / {addresses.length}</b></article></section>
    <div className="grid"><section className="card"><h2>客户主档 <span>Profile</span></h2><dl><Row label="法律名称" value={customer.legalName}/><Row label="公司" value={customer.companyName}/><Row label="主要联系人" value={customer.contactName}/><Row label="电话" value={customer.phone}/><Row label="邮箱" value={customer.email}/><Row label="来源" value={customer.source}/><Row label="付款条款" value={customer.paymentTerms}/><Row label="税务状态" value={customer.taxExemptStatus}/><Row label="语言" value={customer.preferredLanguage}/></dl></section>
      <section className="card"><div className="card-head"><h2>联系人 <span>Contacts</span></h2><button onClick={()=>setContactOpen(value=>!value)}>＋ 联系人</button></div>{contactOpen&&<form onSubmit={submitContact} className="mini-form"><input required placeholder="姓名" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><input placeholder="职位" value={contact.title} onChange={e=>setContact({...contact,title:e.target.value})}/><input placeholder="电话" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/><input type="email" placeholder="邮箱" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/><select value={contact.preferredChannel} onChange={e=>setContact({...contact,preferredChannel:e.target.value})}>{["email","phone","sms","wechat"].map(value=><option key={value}>{value}</option>)}</select><label><input type="checkbox" checked={contact.isPrimary} onChange={e=>setContact({...contact,isPrimary:e.target.checked})}/> 主联系人</label><button disabled={saving}>保存</button></form>}<div className="stack">{contacts.map(item=><article key={item.id}><b>{item.name}{item.isPrimary?" · 主要":""}</b><span>{item.title||item.preferredChannel}</span><small>{item.phoneRaw||"—"} · {item.emailRaw||"—"}</small></article>)}{!contacts.length&&<p>暂无联系人</p>}</div></section>
      <section className="card wide"><div className="card-head"><h2>地址 <span>Addresses</span></h2><button onClick={()=>setAddressOpen(value=>!value)}>＋ 地址</button></div>{addressOpen&&<form onSubmit={submitAddress} className="address-form"><select value={address.addressType} onChange={e=>setAddress({...address,addressType:e.target.value})}>{["billing","shipping","project","other"].map(value=><option key={value}>{value}</option>)}</select><input placeholder="标签" value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/><input required placeholder="地址第一行" value={address.line1} onChange={e=>setAddress({...address,line1:e.target.value})}/><input placeholder="地址第二行" value={address.line2} onChange={e=>setAddress({...address,line2:e.target.value})}/><input required placeholder="城市" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><input placeholder="州/省" value={address.state} onChange={e=>setAddress({...address,state:e.target.value})}/><input placeholder="邮编" value={address.postalCode} onChange={e=>setAddress({...address,postalCode:e.target.value})}/><input placeholder="国家代码" value={address.country} onChange={e=>setAddress({...address,country:e.target.value.toUpperCase()})}/><label><input type="checkbox" checked={address.isDefault} onChange={e=>setAddress({...address,isDefault:e.target.checked})}/> 设为此类型默认地址</label><button disabled={saving}>保存地址</button></form>}<div className="address-grid">{addresses.map(item=><article key={item.id}><b>{item.label||item.addressType}{item.isDefault?" · 默认":""}</b><span>{item.line1}{item.line2?` ${item.line2}`:""}</span><small>{item.city}, {item.state} {item.postalCode} · {item.country}</small></article>)}{!addresses.length&&<p>暂无地址</p>}</div></section>
      <section className="card wide"><h2>订单历史 <span>Orders</span></h2><div className="table"><table><thead><tr><th>订单</th><th>项目</th><th>状态</th><th>总额</th><th>欠款</th><th>更新</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><Link href={`/orders/${order.orderNumber}`}>{order.orderNumber}</Link></td><td>{order.projectName||"—"}</td><td>{order.status}</td><td>{order.grandTotal===undefined?"受权限保护":`${order.currency} ${order.grandTotal.toFixed(2)}`}</td><td>{order.balanceDue===undefined?"受权限保护":`${order.currency} ${order.balanceDue.toFixed(2)}`}</td><td>{new Date(order.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!orders.length&&<p>暂无关联订单</p>}</div></section></div>
    <footer>USD 与 RMB 分别汇总，未进行隐式换算。所有内容来自统一数据库。</footer><style jsx>{styles}</style></main>;
}

function Row({label,value}:{label:string;value:unknown}){return <div><dt>{label}</dt><dd>{String(value||"—")}</dd></div>}
const styles=`.page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:30px;font-family:Arial,"PingFang SC",sans-serif}header,.kpis,.grid,.feedback,footer{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;gap:18px}.actions{display:flex;gap:9px;align-items:flex-start;flex-wrap:wrap}a,button{border:0;border-radius:9px;padding:10px 14px;background:#1f5b49;color:white;text-decoration:none;font-weight:800}h1{font-size:36px;margin:7px 0}h2{margin-top:0}h2 span,p,small,dt{color:#687871}.feedback{background:#edf7f0;padding:12px;border-radius:10px;margin-top:15px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:22px}.kpis article,.card{background:white;border:1px solid #dedbd3;border-radius:16px;padding:18px}.kpis span{display:block;font-size:12px}.kpis b{display:block;font-size:20px;margin-top:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.wide{grid-column:1/-1}.card-head{display:flex;justify-content:space-between;gap:12px}.card-head button{padding:8px 11px}dl div{display:flex;justify-content:space-between;gap:18px;padding:8px 0;border-bottom:1px solid #eeeae3}dd{margin:0;font-weight:700;text-align:right}.stack,.address-grid{display:grid;gap:10px}.stack article,.address-grid article{display:grid;gap:4px;padding:12px;background:#f6f7f4;border-radius:10px}.mini-form,.address-form{display:grid;grid-template-columns:1fr 1fr;gap:9px;padding:12px;background:#f4f2ed;border-radius:12px;margin-bottom:12px}.mini-form input,.mini-form select,.address-form input,.address-form select{box-sizing:border-box;width:100%;border:1px solid #cfd7d2;border-radius:8px;padding:10px;background:white}.address-grid{grid-template-columns:repeat(2,1fr)}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:850px}th,td{padding:11px;border-bottom:1px solid #e8e5de;text-align:left;font-size:13px}td a{background:none;color:#174f3e;padding:0}footer{padding:22px 0;font-size:12px;color:#718078}.state{min-height:100vh;display:grid;place-content:center;text-align:center;background:#f4f2ed;color:#18352c;font-family:Arial,"PingFang SC",sans-serif}.state a{display:inline-block}@media(max-width:760px){.page{padding:15px}header{display:block}.actions{margin-top:12px}.kpis{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.mini-form,.address-form,.address-grid{grid-template-columns:1fr}}`;
