"use client";

export type EncryptedRecord={id:string;iv:number[];cipher:number[]};
const DB_NAME="braun-measure-field-v1",STORE="encrypted",KEY_STORE="keys";

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"});if(!db.objectStoreNames.contains(KEY_STORE))db.createObjectStore(KEY_STORE,{keyPath:"id"})};request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result)})}
async function deviceKey(){if(!globalThis.crypto?.subtle)throw new Error("Secure device encryption unavailable");const db=await openDb(),existing=await new Promise<{id:string;key:CryptoKey}|undefined>((resolve,reject)=>{const request=db.transaction(KEY_STORE).objectStore(KEY_STORE).get("measure-key");request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result)});if(existing?.key)return existing.key;const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);await new Promise<void>((resolve,reject)=>{const request=db.transaction(KEY_STORE,"readwrite").objectStore(KEY_STORE).put({id:"measure-key",key});request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve()});return key}
export async function encryptedPut(id:string,value:unknown){const key=await deviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,plain),record:EncryptedRecord={id,iv:[...iv],cipher:[...new Uint8Array(cipher)]},db=await openDb();await new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,"readwrite").objectStore(STORE).put(record);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve()})}
export async function encryptedGet<T>(id:string){const db=await openDb(),record=await new Promise<EncryptedRecord|undefined>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(id);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result)});if(!record)return null;const key=await deviceKey(),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(record.iv)},key,new Uint8Array(record.cipher));return JSON.parse(new TextDecoder().decode(plain)) as T}
export async function encryptedDelete(id:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve()})}
