export type UnifiedModule = {key:string;zh:string;en:string;descriptionZh:string;descriptionEn:string;href:string;roles:Array<"owner"|"sales"|"factory"|"installer"|"customer">;status:"available"|"migrating"|"planned"};
export const UNIFIED_MODULES:UnifiedModule[]=[
{key:"calculators",zh:"三个报价计算器",en:"3 Pricing Calculators",descriptionZh:"Braun、Jin 与 Z 系列计算器直接入口，立即可用。",descriptionEn:"Direct live access to Braun, Jin and Z-Series calculators.",href:"/calculators",roles:["owner","sales","customer"],status:"available"},
{key:"field-today",zh:"今日现场任务",en:"Today’s Field Tasks",descriptionZh:"真实测量与安装任务。",descriptionEn:"Real Measure and Installation tasks.",href:"/field-today",roles:["owner","sales","installer"],status:"available"},
{key:"customers",zh:"客户与订单",en:"Customers & Orders",descriptionZh:"统一管理客户、项目和订单。",descriptionEn:"Manage customers, projects and orders.",href:"/customers",roles:["owner","sales"],status:"available"},
{key:"smart-measure",zh:"智能测量中心",en:"Smart Measure",descriptionZh:"按项目、房间和 Window 录入精确尺寸。",descriptionEn:"Capture exact dimensions by property, room and Window.",href:"/measure",roles:["owner","sales"],status:"available"},
{key:"manufacturing-drawing",zh:"加工图制作",en:"Manufacturing Drawing",descriptionZh:"按真实 Window 建立加工图。",descriptionEn:"Create manufacturing drawings from real Windows.",href:"/manufacturing-drawing",roles:["owner","sales"],status:"available"},
{key:"manufacturing-drawing-admin",zh:"加工图审批与工厂分配",en:"Drawing Approval & Factory Assignment",descriptionZh:"批准加工图并分配生产工厂。",descriptionEn:"Approve drawings and assign factories.",href:"/manufacturing-drawing-admin",roles:["owner"],status:"available"},
{key:"factory-work-orders",zh:"工厂生产单与运费",en:"Factory Work Orders & Freight",descriptionZh:"生产、质检、运输和运费。",descriptionEn:"Production, QC, freight and receiving.",href:"/factory-work-orders",roles:["owner"],status:"available"},
{key:"invoice-signatures",zh:"Invoice 客户签名",en:"Invoice Signatures",descriptionZh:"发起并跟踪 Invoice 签名。",descriptionEn:"Create and track Invoice signatures.",href:"/invoices",roles:["owner"],status:"available"},
{key:"data-import",zh:"真实数据导入中心",en:"Real Data Import Center",descriptionZh:"导入批发销售和 Jin 汇总 Excel。",descriptionEn:"Import Wholesale Sales and Jin Summary workbooks.",href:"/data-import",roles:["owner"],status:"available"},
{key:"installation",zh:"安装中心",en:"Installation Center",descriptionZh:"安装任务、排期和状态更新。",descriptionEn:"Installation tasks, scheduling and status.",href:"/installations",roles:["owner","sales","installer"],status:"available"},
{key:"resources",zh:"产品与价格中心",en:"Product & Pricing Center",descriptionZh:"产品、价格表和安装资料。",descriptionEn:"Products, price books and installation resources.",href:"/catalog",roles:["owner","sales","factory","installer","customer"],status:"available"},
{key:"z-series-estimate",zh:"Z 系列价格试算",en:"Z-Series Price Estimate",descriptionZh:"正式 USD 产品价格表、折扣和 1/16 英寸尺寸试算。",descriptionEn:"Approved USD price list, discount and 1/16-inch estimate.",href:"/z-series-quote",roles:["owner","sales","customer"],status:"available"},
{key:"search",zh:"全局搜索",en:"Global Search",descriptionZh:"搜索订单、客户、Invoice 和地址。",descriptionEn:"Search orders, customers, invoices and addresses.",href:"/search",roles:["owner","sales","factory","installer","customer"],status:"available"}
];
