"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Category={id:number;code:string;nameZh:string;nameEn:string};
type Product={id:number;sku:string;productType:string;nameZh:string;nameEn:string;status:string;categoryNameZh:string;categoryNameEn:string;defaultUom:string};
const empty={categoryId:"",sku:"",productType:"shutter",nameZh:"",nameEn:"",material:"",primary:"",secondary:"",tertiary:""};

export default function CatalogPage(){
  const [categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[form,setForm]=useState(empty),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[q,setQ]=useState("");
  const load=async()=>{const [c,p]=await Promise.all([fetch("/api/v4/catalog/categories",{cache:"no-store"}),fetch(`/api/v4/catalog/products?q=${encodeURIComponent(q)}`,{cache:"no-store"})]);if(c.status===401||p.status===401){location.href="/login";return}const cd=await c.json(),pd=await p.json();setCategories(cd.categories||[]);setProducts(pd.products||[])};
  // Initial server-backed catalog hydration; later refreshes are explicit user actions.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void load()},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");const shutter=form.productType==="shutter";const spec=shutter?{material:form.material,panelConfiguration:form.primary,louverSize:form.secondary,frameType:form.tertiary}:{blindType:form.primary,material:form.material,orientation:"horizontal",slatOrVaneSize:form.secondary,liftType:"cordless",tiltType:form.tertiary};try{const response=await fetch("/api/v4/catalog/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,categoryId:Number(form.categoryId),spec})});const data=await response.json();if(!response.ok)throw new Error(data.error||"建立失败");setForm(empty);setCreating(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"建立失败")}finally{setSaving(false)}};
  return <main className="page"><header><div><small>BRN-021 · PRODUCT SOURCE OF TRUTH</small><h1>产品与价格中心</h1><p>Shutters、Blinds 与全部产品的统一主档。新产品先以草稿保存，价格发布前不会进入正式报价。</p></div><div><Link href="/hub">返回统一入口</Link><button onClick={()=>setCreating(value=>!value)}>＋ 新建产品</button></div></header>
    {creating&&<form className="card form" onSubmit={submit}><h2>建立产品草稿</h2><div className="grid"><label>分类<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">选择分类</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nameZh} / {c.nameEn}</option>)}</select></label><label>产品类型<select value={form.productType} onChange={e=>setForm({...form,productType:e.target.value})}><option value="shutter">Shutter</option><option value="blind">Blind</option><option value="shade">Shade</option><option value="drapery">Drapery</option><option value="hardware">Hardware</option><option value="service">Service</option></select></label><label>SKU<input required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>中文名称<input required value={form.nameZh} onChange={e=>setForm({...form,nameZh:e.target.value})}/></label><label>英文名称<input required value={form.nameEn} onChange={e=>setForm({...form,nameEn:e.target.value})}/></label><label>材质<input required={form.productType==="shutter"||form.productType==="blind"} value={form.material} onChange={e=>setForm({...form,material:e.target.value})}/></label>{form.productType==="shutter"?<><label>Panel 配置<input required value={form.primary} onChange={e=>setForm({...form,primary:e.target.value})}/></label><label>Louver 尺寸<input required value={form.secondary} onChange={e=>setForm({...form,secondary:e.target.value})}/></label><label>Frame 类型<input required value={form.tertiary} onChange={e=>setForm({...form,tertiary:e.target.value})}/></label></>:form.productType==="blind"?<><label>Blind 类型<input required value={form.primary} onChange={e=>setForm({...form,primary:e.target.value})}/></label><label>Slat / Vane 尺寸<input required value={form.secondary} onChange={e=>setForm({...form,secondary:e.target.value})}/></label><label>Tilt 方式<input required value={form.tertiary} onChange={e=>setForm({...form,tertiary:e.target.value})}/></label></>:null}</div>{error&&<div className="error">{error}</div>}<button disabled={saving}>{saving?"保存中…":"保存草稿"}</button></form>}
    <section className="card"><div className="toolbar"><div><b>{products.length}</b><span> 个产品主档</span></div><form onSubmit={e=>{e.preventDefault();void load()}}><input aria-label="搜索产品" placeholder="搜索 SKU 或名称" value={q} onChange={e=>setQ(e.target.value)}/><button>搜索</button></form></div><div className="table"><table><thead><tr><th>SKU</th><th>产品</th><th>分类</th><th>类型</th><th>单位</th><th>状态</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.sku}</b></td><td>{p.nameZh}<small>{p.nameEn}</small></td><td>{p.categoryNameZh}<small>{p.categoryNameEn}</small></td><td>{p.productType}</td><td>{p.defaultUom}</td><td><span className={`pill ${p.status}`}>{p.status}</span></td></tr>)}</tbody></table>{!products.length&&<div className="empty">还没有产品。Owner 可以先建立 Shutter 或 Blind 草稿。</div>}</div></section><style jsx>{styles}</style></main>;
}
const styles=`.page{min-height:100vh;background:#f4f1ea;color:#24332d;padding:28px;font-family:Arial,"PingFang SC",sans-serif}header{max-width:1200px;margin:auto auto 22px;background:#173f35;color:white;border-radius:20px;padding:28px;display:flex;justify-content:space-between;gap:20px;align-items:end}small{display:block;color:#78857f;font-size:12px;margin-top:4px}header small{color:#d4b46d;letter-spacing:1px}h1{margin:7px 0;font-size:32px}header p{margin:0;color:#bed0c8;max-width:720px;line-height:1.6}header>div:last-child{display:flex;gap:9px;flex-wrap:wrap}a,button{border:0;border-radius:9px;padding:10px 14px;background:#d7ab58;color:#173f35;text-decoration:none;font-weight:800;cursor:pointer}.card{max-width:1200px;margin:0 auto 18px;background:white;border:1px solid #ded9ce;border-radius:18px;padding:20px;box-sizing:border-box}.form h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(220px,100%),1fr));gap:13px}.grid label{display:grid;gap:6px;font-size:12px;font-weight:800}input,select{box-sizing:border-box;width:100%;border:1px solid #cbd5cf;border-radius:9px;padding:10px;background:white;font:inherit}.form>button{margin-top:16px;background:#1f5b49;color:white}.error{margin-top:13px;padding:10px;background:#fff0ec;color:#963c31;border-radius:9px}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.toolbar b{font-size:24px}.toolbar form{display:flex;gap:7px}.toolbar button{background:#1f5b49;color:white}.table{overflow:auto;margin-top:15px}table{border-collapse:collapse;width:100%;min-width:760px}th,td{text-align:left;padding:12px;border-top:1px solid #edf0ed;font-size:13px}th{color:#78857f;font-size:11px}.pill{padding:5px 8px;border-radius:999px;background:#fff1d7;color:#8a5a00}.pill.active{background:#e4f3eb;color:#17603f}.empty{text-align:center;padding:36px;color:#77837d}@media(max-width:650px){.page{padding:14px}header{align-items:start;flex-direction:column;padding:21px}h1{font-size:26px}.card{padding:15px}}`;
