import { and, eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/db";
import { invoiceSignatureEvents, invoiceSignatureRequests, invoiceSignatures, invoiceVersions } from "@/db/schema";
import { sha256 } from "@/lib/v4-auth";

async function lookup(token:string){const tokenHash=await sha256(token),db=await getDb();const rows=await db.select({request:invoiceSignatureRequests,version:invoiceVersions}).from(invoiceSignatureRequests).innerJoin(invoiceVersions,eq(invoiceSignatureRequests.invoiceVersionId,invoiceVersions.id)).where(eq(invoiceSignatureRequests.tokenHash,tokenHash)).limit(1);return {db,row:rows[0]}}
const publicInvoice=(snapshotJson:string)=>{const s=JSON.parse(snapshotJson) as Record<string,unknown>;return {invoiceNumber:s.invoiceNumber,orderNumber:s.orderNumber,projectName:s.projectName,wholesaleTotal:s.wholesaleTotal,paymentCurrency:s.paymentCurrency,customerEmail:s.customerEmail}}

export async function GET(_request:NextRequest,context:{params:Promise<{token:string}>}){const {token}=await context.params;if(!/^[0-9a-f]{64}$/.test(token))return NextResponse.json({error:"签名链接无效"},{status:400});const {db,row}=await lookup(token);if(!row)return NextResponse.json({error:"签名链接无效"},{status:404});let status=row.request.status;if(status==="pending"&&new Date(row.request.expiresAt)<=new Date()){status="expired";await db.update(invoiceSignatureRequests).set({status}).where(eq(invoiceSignatureRequests.id,row.request.id));await db.insert(invoiceSignatureEvents).values({requestId:row.request.id,eventType:"expired",actorType:"system"})}if(status==="pending"){const now=new Date().toISOString();await db.update(invoiceSignatureRequests).set({status:"viewed",viewedAt:now}).where(eq(invoiceSignatureRequests.id,row.request.id));await db.insert(invoiceSignatureEvents).values({requestId:row.request.id,eventType:"viewed",actorType:"customer"});status="viewed"}return NextResponse.json({request:{status,expiresAt:row.request.expiresAt,signerEmail:row.request.signerEmail},invoice:{...publicInvoice(row.version.snapshotJson),version:row.version.version,documentSha256:row.version.documentSha256}})}

export async function POST(request:NextRequest,context:{params:Promise<{token:string}>}){const {token}=await context.params;if(!/^[0-9a-f]{64}$/.test(token))return NextResponse.json({error:"签名链接无效"},{status:400});const {db,row}=await lookup(token);if(!row)return NextResponse.json({error:"签名链接无效"},{status:404});if(!["pending","viewed"].includes(row.request.status))return NextResponse.json({error:`此请求已${row.request.status}`},{status:409});if(new Date(row.request.expiresAt)<=new Date())return NextResponse.json({error:"签名链接已过期"},{status:410});let body:{action?:string;signerName?:string;consent?:boolean;timezone?:string;points?:unknown;reason?:string};try{body=await request.json()}catch{return NextResponse.json({error:"请求格式错误"},{status:400})}const now=new Date().toISOString();if(body.action==="decline"){const reason=String(body.reason||"").trim().slice(0,500);if(!reason)return NextResponse.json({error:"请填写拒签原因"},{status:400});await db.update(invoiceSignatureRequests).set({status:"declined",declinedAt:now}).where(eq(invoiceSignatureRequests.id,row.request.id));await db.insert(invoiceSignatureEvents).values({requestId:row.request.id,eventType:"declined",actorType:"customer",metadataJson:JSON.stringify({reason})});return NextResponse.json({ok:true,status:"declined"})}
  const signerName=String(body.signerName||"").replace(/\s+/g," ").trim().slice(0,160),points=Array.isArray(body.points)?body.points:[];if(!signerName||body.consent!==true||points.length<2||points.length>5000)return NextResponse.json({error:"请填写签名姓名、同意条款并完成手写签名"},{status:400});const pointsJson=JSON.stringify(points);if(pointsJson.length>150_000)return NextResponse.json({error:"签名数据过大，请清除后重新签名"},{status:413});const verificationCode=crypto.randomUUID().replace(/-/g,"").slice(0,12).toUpperCase(),ipHash=await sha256(request.headers.get("cf-connecting-ip")||""),uaHash=await sha256(request.headers.get("user-agent")||"");try{await db.insert(invoiceSignatures).values({requestId:row.request.id,invoiceVersionId:row.version.id,signerName,signerEmail:row.request.signerEmail,signaturePointsJson:pointsJson,consentTextVersion:"v1",signedAtUtc:now,timezone:String(body.timezone||"UTC").slice(0,80),documentSha256:row.version.documentSha256,verificationCode,ipAddressHash:ipHash,userAgentHash:uaHash});await db.update(invoiceSignatureRequests).set({status:"signed",signedAt:now}).where(and(eq(invoiceSignatureRequests.id,row.request.id),eq(invoiceSignatureRequests.status,row.request.status)));await db.insert(invoiceSignatureEvents).values({requestId:row.request.id,eventType:"signed",actorType:"customer",metadataJson:JSON.stringify({verificationCode,documentSha256:row.version.documentSha256})});return NextResponse.json({ok:true,status:"signed",verificationCode,signedAt:now})}catch{return NextResponse.json({error:"此 Invoice 已完成签署"},{status:409})}}
