"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type SignatureRequest={id:number;status:string;signerEmail:string;expiresAt:string;viewedAt:string|null;signedAt:string|null;declinedAt:string|null;revokedAt:string|null;createdAt:string};
type Invoice={id:number;orderNumber:string;invoiceNumber:string;customerEmail:string;projectName:string;wholesaleTotal:number;paymentCurrency:string;paymentStatus:string;amountPaid:number;confirmedAt:string|null;signatureRequest:SignatureRequest|null};
type LinkRecord={url:string;requestId:number};

const statusText:Record<string,string>={pending:"等待客户查看",viewed:"客户已查看",signed:"已签署",declined:"客户已拒签",expired:"已过期",revoked:"已撤销"};

export default function InvoicesPage(){
  const [invoices,setInvoices]=useState<Invoice[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[working,setWorking]=useState<string|null>(null),[links,setLinks]=useState<Record<string,LinkRecord>>({}),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/v4/invoices",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"无法读取 Invoice");setInvoices(data.invoices||[])}catch(reason){setError(reason instanceof Error?reason.message:"无法读取 Invoice")}finally{setLoading(false)}},[]);
  // Keep this protected management view synchronized with the latest D1 records.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>{const value=query.trim().toLowerCase();if(!value)return invoices;return invoices.filter(invoice=>[invoice.invoiceNumber,invoice.orderNumber,invoice.customerEmail,invoice.projectName].some(field=>String(field||"").toLowerCase().includes(value)))},[invoices,query]);
  const copy=async(invoiceNumber:string)=>{const record=links[invoiceNumber];if(!record)return;try{await navigator.clipboard.writeText(record.url);setMessage(`Invoice ${invoiceNumber} 的客户签名链接已复制`)}catch{setError("浏览器无法复制，请手动复制显示的链接")}};
  const requestSignature=async(invoice:Invoice)=>{setWorking(invoice.invoiceNumber);setError("");setMessage("");try{const response=await fetch(`/api/v4/invoices/${encodeURIComponent(invoice.invoiceNumber)}/signature-requests`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()}});const data=await response.json();if(!response.ok)throw new Error(data.error||"无法创建签名请求");const url=new URL(data.signaturePath,location.origin).toString();setLinks(current=>({...current,[invoice.invoiceNumber]:{url,requestId:data.request.id}}));try{await navigator.clipboard.writeText(url);setMessage(`Invoice ${invoice.invoiceNumber} 的签名请求已建立，客户链接已复制`)}catch{setMessage(`Invoice ${invoice.invoiceNumber} 的签名请求已建立，请复制下方链接`)}await load()}catch(reason){setError(reason instanceof Error?reason.message:"无法创建签名请求")}finally{setWorking(null)}};
  return <main className="page"><header><div><small>INVOICE SIGNATURE CONTROL</small><h1>Invoice 与客户签名</h1><p>从真实订单读取五位数 Invoice，由老板发起客户签名并跟踪查看、签署或拒签状态。</p></div><div className="actions"><Link href="/hub">返回老板门户</Link><button onClick={()=>void load()}>刷新状态</button></div></header>
    <section className="toolbar"><input aria-label="搜索 Invoice" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索 Invoice、订单、客户邮箱或项目"/><b>{filtered.length} 个 Invoice</b></section>
    {message&&<div className="message" role="status">{message}</div>}{error&&<div className="error" role="alert">{error}</div>}
    <section className="card"><div className="table"><table><thead><tr><th>Invoice / 订单</th><th>客户 / 项目</th><th>金额 / 付款</th><th>签名状态</th><th>操作</th></tr></thead><tbody>{filtered.map(invoice=>{const request=invoice.signatureRequest,record=links[invoice.invoiceNumber],active=request&&["pending","viewed"].includes(request.status);return <tr key={invoice.id}><td><b>Invoice {invoice.invoiceNumber}</b><small>Order {invoice.orderNumber}</small></td><td>{invoice.customerEmail}<small>{invoice.projectName||"—"}</small></td><td><b>{invoice.paymentCurrency.toUpperCase()} {Number(invoice.wholesaleTotal).toFixed(2)}</b><small>{invoice.paymentStatus} · 已付 {Number(invoice.amountPaid).toFixed(2)}</small></td><td>{request?<><span className={`pill ${request.status}`}>{statusText[request.status]||request.status}</span><small>{request.signedAt?`签署于 ${new Date(request.signedAt).toLocaleString()}`:`有效至 ${new Date(request.expiresAt).toLocaleString()}`}</small></>:<span className="muted">尚未请求</span>}</td><td><div className="row-actions">{record?<button onClick={()=>void copy(invoice.invoiceNumber)}>复制客户链接</button>:<button disabled={working===invoice.invoiceNumber||Boolean(active)} onClick={()=>void requestSignature(invoice)}>{working===invoice.invoiceNumber?"正在建立…":active?"已有有效请求":"请求客户签名"}</button>}</div>{record&&<a className="signature-url" href={record.url} target="_blank" rel="noreferrer">打开客户签名页</a>}{active&&!record&&<small className="notice">为保护安全，旧链接不能从数据库恢复；请使用创建时保存的链接。</small>}</td></tr>})}</tbody></table>{loading&&<div className="empty">正在读取真实 Invoice…</div>}{!loading&&!filtered.length&&<div className="empty">没有符合条件的 Invoice</div>}</div></section>
    <style jsx>{`.page{min-height:100vh;background:#f4f2ed;color:#18352c;padding:30px;font-family:Arial,"PingFang SC",sans-serif}header,.toolbar,.message,.error,.card{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;gap:20px}h1{font-size:36px;margin:7px 0}small{display:block;color:#6b7a74;margin-top:5px}.actions,.row-actions{display:flex;gap:9px;align-items:flex-start;flex-wrap:wrap}a,button{border:0;border-radius:9px;padding:10px 14px;background:#1f5b49;color:white;text-decoration:none;font-weight:800;cursor:pointer}.toolbar{display:flex;gap:15px;align-items:center;margin-top:22px}.toolbar input{box-sizing:border-box;flex:1;border:1px solid #cfd7d2;border-radius:10px;padding:12px;background:white}.message,.error{box-sizing:border-box;margin-top:14px;padding:13px;border-radius:10px}.message{background:#e5f3eb;color:#17603f}.error{background:#fff0ec;color:#95392e}.card{box-sizing:border-box;background:white;border:1px solid #dedbd3;border-radius:18px;padding:20px;margin-top:16px}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1050px}th,td{padding:13px;border-bottom:1px solid #e8e5de;text-align:left;font-size:13px;vertical-align:top}.pill{display:inline-block;background:#e8f0eb;border-radius:999px;padding:6px 9px}.pill.signed{background:#dff3e7;color:#17603f}.pill.declined,.pill.expired,.pill.revoked{background:#f3e9e4;color:#873d31}.muted{color:#77817c}.signature-url{display:inline-block;background:none;color:#174f3e;padding:7px 0 0}.notice{max-width:260px;color:#8a5a00}button:disabled{opacity:.5;cursor:not-allowed}.empty{text-align:center;padding:35px;color:#74817b}@media(max-width:760px){.page{padding:15px}header{display:block}.actions{margin-top:12px}.toolbar{align-items:stretch;flex-direction:column}.card{padding:12px}}`}</style>
  </main>;
}
