"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

export default function SetupOwnerPage(){
  const [form,setForm]=useState({displayName:"",email:"",username:"",password:"",confirmPassword:""}),[showPassword,setShowPassword]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");if(form.password!==form.confirmPassword){setError("两次密码不一致");return}if(saving)return;setSaving(true);try{const response=await fetch("/api/v4/auth/bootstrap-owner",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:form.displayName,email:form.email,username:form.username,password:form.password})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Owner 初始化失败");setDone(true)}catch(reason){setError(reason instanceof Error?reason.message:"Owner 初始化失败")}finally{setSaving(false)}};
  if(done)return <main className="page"><section className="card"><small>OWNER READY</small><h1>老板账号已建立</h1><p>初始化入口现已自动关闭。请使用刚才设置的账号登录统一门户。</p><Link className="primary" href="/login">前往登录 →</Link></section><style jsx>{styles}</style></main>;
  return <main className="page"><form className="card" onSubmit={submit}><small>ONE-TIME OWNER SETUP</small><h1>首次建立老板账号</h1><p>此页面只允许私人站点 Owner 使用，并且只能成功一次。密码至少 10 位，不会保存到浏览器配置。</p><label>显示名称<input required value={form.displayName} onChange={event=>setForm({...form,displayName:event.target.value})}/></label><label>邮箱<input required type="email" autoComplete="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>登录用户名<input required autoComplete="username" value={form.username} onChange={event=>setForm({...form,username:event.target.value})}/></label><label>密码<span className="password-field"><input required minLength={10} type={showPassword?"text":"password"} autoComplete="new-password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/><button className="reveal" type="button" aria-pressed={showPassword} onClick={()=>setShowPassword(value=>!value)}>{showPassword?"隐藏":"显示"}</button></span></label><label>确认密码<input required minLength={10} type={showPassword?"text":"password"} autoComplete="new-password" value={form.confirmPassword} onChange={event=>setForm({...form,confirmPassword:event.target.value})}/></label>{error&&<div className="error">{error}</div>}<button disabled={saving}>{saving?"正在建立…":"建立 Owner 账号"}</button><Link className="back" href="/login">返回登录</Link></form><style jsx>{styles}</style></main>;
}

const styles=`.page{min-height:100vh;display:grid;place-items:center;background:#f4f1ea;color:#173f35;padding:20px;font-family:Arial,"PingFang SC",sans-serif}.card{box-sizing:border-box;width:min(500px,100%);background:#fff;border:1px solid #dcd8cd;border-radius:20px;padding:28px;box-shadow:0 20px 60px rgba(25,55,45,.1)}small{letter-spacing:1px;color:#6b7a74}h1{margin:9px 0;font-size:29px}p{color:#68746e;line-height:1.6}label{display:grid;gap:7px;margin-top:13px;font-size:13px;font-weight:800}input{box-sizing:border-box;width:100%;padding:11px;border:1px solid #cbd5cf;border-radius:10px;font:inherit}.password-field{display:grid;grid-template-columns:1fr auto;gap:8px}.reveal{width:auto;margin:0;padding:0 14px;background:#e6eee9;color:#174f3e}button,.primary{display:block;box-sizing:border-box;width:100%;border:0;border-radius:10px;padding:12px;margin-top:18px;background:#1f5b49;color:#fff;text-align:center;text-decoration:none;font-weight:800;cursor:pointer}button:disabled{opacity:.5}.error{background:#fff0ec;color:#963c31;padding:11px;border-radius:9px;margin-top:14px}.back{display:block;text-align:center;margin-top:15px;color:#1f5b49}`;
