"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type User={id:number;role:string};
type Job={id:number;orderNumber:string;projectName:string;installerId:number;installerName:string};
type Package={id:number;installationJobId:number;state:string;sourceVersion:number;snapshotSha256:string;expiresAt:string;orderNumber:string;projectName:string;assignee:string;snapshot:unknown};
type OfflineOperation={clientOperationId:string;packageId:number;operationType:"note_draft";baseSourceVersion:number;payload:{note:string};queuedAt:string};

const database=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open("braun-field-v1",2);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("packages"))db.createObjectStore("packages",{keyPath:"id"});if(!db.objectStoreNames.contains("operations"))db.createObjectStore("operations",{keyPath:"clientOperationId"})};request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result)});
const put=async(storeName:"packages"|"operations",value:unknown)=>{const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(storeName,"readwrite");tx.objectStore(storeName).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})};
const remove=async(id:string)=>{const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("operations","readwrite");tx.objectStore("operations").delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})};
const queued=async()=>{const db=await database();return new Promise<OfflineOperation[]>((resolve,reject)=>{const request=db.transaction("operations").objectStore("operations").getAll();request.onsuccess=()=>resolve(request.result as OfflineOperation[]);request.onerror=()=>reject(request.error)})};

export default function Page(){
  const[user,setUser]=useState<User|null>(null),[jobs,setJobs]=useState<Job[]>([]),[packages,setPackages]=useState<Package[]>([]),[jobId,setJobId]=useState(0),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[notes,setNotes]=useState<Record<number,string>>({}),[queue,setQueue]=useState<OfflineOperation[]>([]);
  const refreshQueue=async()=>setQueue(await queued());
  const load=async()=>{const me=await(await fetch("/api/v4/auth/me",{cache:"no-store"})).json();setUser(me.user||null);const response=await fetch("/api/v4/offline-job-packages",{cache:"no-store"}),data=await response.json();setPackages(data.packages||[]);if(me.user?.role==="owner"){const jobData=await(await fetch("/api/v4/installations",{cache:"no-store"})).json();setJobs(jobData.jobs||[]);setJobId((current:number)=>current||jobData.jobs?.[0]?.id||0)}await refreshQueue()};
  // Initial server and device synchronization is intentionally performed once on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{setOnline(navigator.onLine);const change=()=>setOnline(navigator.onLine);window.addEventListener("online",change);window.addEventListener("offline",change);void load();return()=>{window.removeEventListener("online",change);window.removeEventListener("offline",change)}},[]);
  const prepare=async()=>{const job=jobs.find(item=>item.id===jobId);if(!job)return;setBusy(true);const response=await fetch("/api/v4/offline-job-packages",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({installationJobId:job.id,assignedUserId:job.installerId})}),data=await response.json();setMessage(response.ok?"Offline package prepared / 离线包已准备":data.error);setBusy(false);if(response.ok)await load()};
  const download=async(pkg:Package)=>{setBusy(true);try{await put("packages",{...pkg,cachedAt:new Date().toISOString()});const response=await fetch("/api/v4/offline-job-packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageId:pkg.id,action:"downloaded"})}),data=await response.json();setMessage(response.ok?"Saved to this device / 已保存到本机":data.error);if(response.ok)await load()}catch{setMessage("This browser could not create the offline cache / 无法建立离线缓存")}finally{setBusy(false)}};
  const queueNote=async(pkg:Package)=>{const note=(notes[pkg.id]||"").trim();if(!note)return;const operation:OfflineOperation={clientOperationId:crypto.randomUUID(),packageId:pkg.id,operationType:"note_draft",baseSourceVersion:pkg.sourceVersion,payload:{note},queuedAt:new Date().toISOString()};await put("operations",operation);setNotes(current=>({...current,[pkg.id]:""}));setMessage("Draft queued on this device / 草稿已进入本机队列");await refreshQueue()};
  const sync=async(pkg:Package)=>{const items=queue.filter(item=>item.packageId===pkg.id);if(!items.length)return;setBusy(true);let synced=0,conflicts=0;for(const operation of items){try{const response=await fetch("/api/v4/offline-job-packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sync",...operation})});if(response.ok){await remove(operation.clientOperationId);synced++}else if(response.status===409)conflicts++}catch{break}}setBusy(false);await refreshQueue();await load();setMessage(conflicts?`${conflicts} conflict(s) require review / ${conflicts} 个冲突需要审核`:`${synced} draft(s) synchronized / 已同步 ${synced} 个草稿`)};
  const revoke=async(id:number)=>{if(!confirm("Revoke this device package? / 撤销此离线包？"))return;const response=await fetch("/api/v4/offline-job-packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageId:id,action:"revoke"})}),data=await response.json();setMessage(response.ok?"Package revoked / 已撤销":data.error);await load()};
  return <main><header><div><small>SPRINT 14.1 · #204</small><h1>离线现场包 / Offline Field Packages</h1><p>最小授权快照、离线草稿队列、幂等同步与版本冲突保护。</p></div><div className={`network ${online?"online":"offline"}`}>{online?"Online / 在线":"Offline / 离线"}</div><Link href="/hub">Hub</Link></header>{message&&<p className="message">{message}</p>}{user?.role==="owner"&&<section className="card prepare"><h2>Prepare assigned package</h2><select value={jobId} onChange={event=>setJobId(+event.target.value)}>{jobs.map(job=><option key={job.id} value={job.id}>{job.orderNumber} · {job.projectName} · {job.installerName}</option>)}</select><button disabled={!jobId||busy||!online} onClick={()=>void prepare()}>Prepare / Refresh</button></section>}<section className="list">{!packages.length&&<article><h2>No assigned offline packages</h2><p>没有已分配离线包。系统不会生成演示任务。</p></article>}{packages.map(pkg=>{const pending=queue.filter(item=>item.packageId===pkg.id);return <article key={pkg.id}><div className="title"><div><small>{pkg.orderNumber} · Package #{pkg.id}</small><h2>{pkg.projectName}</h2></div><strong data-state={pkg.state}>{pkg.state.replaceAll("_"," ")}</strong></div><dl><div><dt>Assigned</dt><dd>{pkg.assignee}</dd></div><div><dt>Source version</dt><dd>V{pkg.sourceVersion}</dd></div><div><dt>Expires</dt><dd>{new Date(pkg.expiresAt).toLocaleString()}</dd></div><div><dt>Device queue</dt><dd>{pending.length} draft(s)</dd></div></dl><code className="hash">SHA-256 {pkg.snapshotSha256}</code><div className="draft"><label>Offline note draft / 离线备注草稿<textarea value={notes[pkg.id]||""} onChange={event=>setNotes(current=>({...current,[pkg.id]:event.target.value}))}/></label><button disabled={!notes[pkg.id]?.trim()||pkg.state==="expired_revoked"} onClick={()=>void queueNote(pkg)}>Queue draft / 保存草稿</button></div>{pending.map(item=><p className="queued" key={item.clientOperationId}><span>{item.payload.note}</span><time>{new Date(item.queuedAt).toLocaleString()}</time></p>)}<div className="actions"><button disabled={busy||!online||pkg.state==="expired_revoked"} onClick={()=>void download(pkg)}>Download to this device</button><button disabled={busy||!online||!pending.length||pkg.state==="expired_revoked"} onClick={()=>void sync(pkg)}>Sync {pending.length||""}</button>{user?.role==="owner"&&<button className="danger" disabled={pkg.state==="expired_revoked"} onClick={()=>void revoke(pkg.id)}>Revoke</button>}</div><p className="truth">Queued changes remain drafts. They never directly post measurements, signatures, payments or completion.</p></article>})}</section><style jsx>{styles}</style></main>;
}

const styles=`main{min-height:100vh;background:#f3f0e9;color:#173c31;padding:20px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.list,.message{max-width:1050px;margin:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:24px;display:flex;gap:10px;align-items:flex-start;justify-content:space-between}a,button{border:0;border-radius:9px;padding:10px 13px;background:#ddb158;color:#173f35;text-decoration:none;font-weight:800}button:disabled{opacity:.45}.network{border-radius:999px;padding:8px 11px;font-weight:800}.network.online{background:#d7ebdf;color:#174b37}.network.offline{background:#ffe0d8;color:#8a2f25}.message{margin-top:12px;background:#e6f1eb;padding:11px}.card,article{margin-top:14px;background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px}.prepare{display:grid;grid-template-columns:1fr auto;gap:10px}.prepare h2{grid-column:1/-1}.prepare select,textarea{padding:11px;border:1px solid #bdc9c3;border-radius:9px}.list{display:grid;gap:12px}.title{display:flex;justify-content:space-between}.title h2{margin:5px 0}.title strong{height:max-content;background:#e7eee9;border-radius:999px;padding:7px 10px}.title strong[data-state="conflict"]{background:#ffe0d8;color:#922}.title strong[data-state="expired_revoked"]{background:#e5e5e5;color:#666}dl{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}dl div{background:#f3f5f2;padding:10px;border-radius:9px}dt{color:#718078;font-size:12px}dd{margin:5px 0 0;word-break:break-word}.hash{display:block;background:#f3f5f2;padding:9px;word-break:break-all}.draft{display:grid;grid-template-columns:1fr auto;gap:9px;margin-top:12px;align-items:end}.draft label{display:grid;gap:5px;font-weight:700}.queued{display:flex;justify-content:space-between;background:#fff4d9;padding:9px}.queued time{color:#718078;font-size:12px}.actions{display:flex;gap:9px;margin-top:12px}.danger{background:#a5392f;color:white}.truth{color:#68766f;font-size:13px}@media(max-width:700px){main{padding:10px}header{display:grid}.prepare,dl,.draft{grid-template-columns:1fr}.prepare h2{grid-column:1}.title{display:block}.actions{flex-direction:column}.queued{display:grid}}`;
