"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type User={id:number;role:string};
type Job={id:number;orderNumber:string;projectName:string;installerId:number;installerName:string;scheduledStart:string};
type Package={id:number;installationJobId:number;assignedUserId:number;state:string;sourceVersion:number;snapshotSha256:string;expiresAt:string;downloadedAt:string|null;lastSyncedAt:string|null;orderNumber:string;projectName:string;assignee:string;snapshot:unknown};

const saveOffline=async(pkg:Package)=>new Promise<void>((resolve,reject)=>{const open=indexedDB.open("braun-field-v1",1);open.onupgradeneeded=()=>open.result.createObjectStore("packages",{keyPath:"id"});open.onerror=()=>reject(open.error);open.onsuccess=()=>{const tx=open.result.transaction("packages","readwrite");tx.objectStore("packages").put({...pkg,cachedAt:new Date().toISOString()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}});

export default function Page(){
  const[user,setUser]=useState<User|null>(null),[jobs,setJobs]=useState<Job[]>([]),[packages,setPackages]=useState<Package[]>([]),[jobId,setJobId]=useState(0),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{const me=await(await fetch("/api/v4/auth/me",{cache:"no-store"})).json();setUser(me.user||null);const packageResponse=await fetch("/api/v4/offline-job-packages",{cache:"no-store"}),packageData=await packageResponse.json();setPackages(packageData.packages||[]);if(me.user?.role==="owner"){const jobData=await(await fetch("/api/v4/installations",{cache:"no-store"})).json();setJobs(jobData.jobs||[]);setJobId((current:number)=>current||jobData.jobs?.[0]?.id||0)}};
  // Initial server synchronization is intentionally performed once on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[]);
  const prepare=async()=>{const job=jobs.find(item=>item.id===jobId);if(!job)return;setBusy(true);const response=await fetch("/api/v4/offline-job-packages",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({installationJobId:job.id,assignedUserId:job.installerId})}),data=await response.json();setMessage(response.ok?"Offline package prepared / 离线包已准备":data.error);setBusy(false);if(response.ok)await load()};
  const download=async(pkg:Package)=>{setBusy(true);try{await saveOffline(pkg);const response=await fetch("/api/v4/offline-job-packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageId:pkg.id,action:"downloaded"})}),data=await response.json();setMessage(response.ok?"Saved to this device / 已保存到本机":data.error);if(response.ok)await load()}catch{setMessage("This browser could not create the offline cache / 无法建立离线缓存")}finally{setBusy(false)}};
  const revoke=async(id:number)=>{if(!confirm("Revoke this device package? / 撤销此离线包？"))return;const response=await fetch("/api/v4/offline-job-packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageId:id,action:"revoke"})}),data=await response.json();setMessage(response.ok?"Package revoked / 已撤销":data.error);await load()};
  return <main><header><div><small>SPRINT 14.1 · #204</small><h1>离线现场包 / Offline Field Packages</h1><p>只缓存已分配任务的最小授权快照；状态、版本、有效期和冲突必须明确可见。</p></div><Link href="/hub">Hub</Link></header>{message&&<p className="message">{message}</p>}{user?.role==="owner"&&<section className="card prepare"><h2>Prepare assigned package</h2><select value={jobId} onChange={event=>setJobId(+event.target.value)}>{jobs.map(job=><option key={job.id} value={job.id}>{job.orderNumber} · {job.projectName} · {job.installerName}</option>)}</select><button disabled={!jobId||busy} onClick={()=>void prepare()}>Prepare / Refresh</button></section>}<section className="list">{!packages.length&&<article><h2>No assigned offline packages</h2><p>没有已分配离线包。系统不会生成演示任务。</p></article>}{packages.map(pkg=><article key={pkg.id}><div className="title"><div><small>{pkg.orderNumber} · Package #{pkg.id}</small><h2>{pkg.projectName}</h2></div><strong data-state={pkg.state}>{pkg.state.replaceAll("_"," ")}</strong></div><dl><div><dt>Assigned</dt><dd>{pkg.assignee}</dd></div><div><dt>Source version</dt><dd>V{pkg.sourceVersion}</dd></div><div><dt>Expires</dt><dd>{new Date(pkg.expiresAt).toLocaleString()}</dd></div><div><dt>SHA-256</dt><dd><code>{pkg.snapshotSha256.slice(0,16)}…</code></dd></div></dl><div className="actions"><button disabled={busy||pkg.state==="expired_revoked"} onClick={()=>void download(pkg)}>Download to this device</button>{user?.role==="owner"&&<button className="danger" disabled={pkg.state==="expired_revoked"} onClick={()=>void revoke(pkg.id)}>Revoke</button>}</div><p className="truth">Offline changes are queued as drafts only. Protected records are never silently posted.</p></article>)}</section><style jsx>{styles}</style></main>;
}

const styles=`main{min-height:100vh;background:#f3f0e9;color:#173c31;padding:20px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.list,.message{max-width:1050px;margin:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:24px;display:flex;justify-content:space-between}a,button{border:0;border-radius:9px;padding:10px 13px;background:#ddb158;color:#173f35;text-decoration:none;font-weight:800}.message{margin-top:12px;background:#e6f1eb;padding:11px}.card,article{margin-top:14px;background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px}.prepare{display:grid;grid-template-columns:1fr auto;gap:10px}.prepare h2{grid-column:1/-1}.prepare select{padding:11px;border:1px solid #bdc9c3;border-radius:9px}.list{display:grid;gap:12px}.title{display:flex;justify-content:space-between}.title h2{margin:5px 0}.title strong{height:max-content;background:#e7eee9;border-radius:999px;padding:7px 10px}.title strong[data-state="conflict"]{background:#ffe0d8;color:#922}.title strong[data-state="expired_revoked"]{background:#e5e5e5;color:#666}dl{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}dl div{background:#f3f5f2;padding:10px;border-radius:9px}dt{color:#718078;font-size:12px}dd{margin:5px 0 0;word-break:break-word}.actions{display:flex;gap:9px}.danger{background:#a5392f;color:white}.truth{color:#68766f;font-size:13px}@media(max-width:700px){main{padding:10px}header{display:block}.prepare,dl{grid-template-columns:1fr}.prepare h2{grid-column:1}.title{display:block}.actions{flex-direction:column}}`;
