"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {encryptedGet,encryptedPut} from "@/lib/offline-measure-device";
import {requiredMeasureFields} from "@/lib/measure-product-requirements";

type Value={fieldKey:string};type Version={id:number;version:number;status:string;productType:string;mountType:string;mediaCount:number;values:Value[]};type Win={id:number;code:string;versions:Version[]};type Room={id:number;name:string;windows:Win[]};type Property={id:number;name:string;address:string;rooms:Room[]};type Workspace={properties:Property[];cachedAt:string};type Draft={id:string;propertyId:number;windowId:number;windowCode:string;reviewed?:boolean;queuedAt:string};

export default function FieldMeasureAudit(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[propertyId,setPropertyId]=useState(0),[lookup,setLookup]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const cached=await encryptedGet<Workspace>("workspace"),queued=await encryptedGet<Draft[]>("drafts");if(cached)setWorkspace(cached);if(queued)setDrafts(queued);try{const response=await fetch("/api/v4/measure/workspace",{cache:"no-store"});if(response.status===401){location.href="/login";return}if(!response.ok)throw new Error();const data=await response.json(),fresh={properties:data.properties||[],cachedAt:new Date().toISOString()};await encryptedPut("workspace",fresh);setWorkspace(fresh);setMessage("已使用服务器最新工作区复核 / Reviewing latest server workspace")}catch{setMessage(cached?"离线复核设备加密缓存 / Auditing encrypted offline cache":"首次使用需要联网 / Connect once to download workspace")}};
 // Initial asynchronous hydration synchronizes React with encrypted IndexedDB and the server workspace.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const properties=workspace?.properties||[],pid=properties.some(item=>item.id===propertyId)?propertyId:properties[0]?.id||0,property=properties.find(item=>item.id===pid),rooms=property?.rooms||[],rows=rooms.flatMap(room=>room.windows.map(item=>{const latest=item.versions?.[0],keys=new Set(latest?.values?.map(value=>value.fieldKey)||[]),missing=latest?requiredMeasureFields(latest.productType,latest.mountType).filter(key=>!keys.has(key)):[],draft=drafts.find(candidate=>candidate.windowId===item.id),hasPhoto=Boolean(latest?.mediaCount),complete=Boolean(latest&&!missing.length&&hasPhoto);return {room,item,latest,draft,missing,hasPhoto,complete}})),matches=lookup.trim()?rows.filter(row=>row.item.code.toUpperCase().includes(lookup.trim().toUpperCase())):[],blockers=rows.filter(row=>!row.complete||row.draft).length+rooms.filter(room=>!room.windows.length).length;
 const status=(row:typeof rows[number])=>row.draft?(row.draft.reviewed?"reviewed draft pending sync / 已复核待同步":"draft review required / 草稿待复核"):!row.latest?"measurement missing / 尚未测量":row.missing.length?`V${row.latest.version} missing: ${row.missing.join(", ")}`:!row.hasPhoto?`V${row.latest.version} photo required / 缺少现场照片`:`server V${row.latest.version} complete / 服务器记录完整`;
 return <main><header><div><small>SPRINT 16.1 · #246</small><h1>现场离开前复核 / Field Exit Audit</h1><p>逐个检查真实 Room 与 Window。设备草稿、产品必填尺寸或精确版本照片缺失都会阻止“可离场”。</p></div><nav><Link href="/field-measure">Measure</Link><Link href="/field-measure-media">Photos</Link><Link href="/hub">Hub</Link></nav></header>{message&&<p className="message">{message}</p>}<section className="card controls"><label>Property<select value={pid} onChange={e=>{setPropertyId(+e.target.value);setLookup("")}}>{properties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Window 编号查找 / Window code lookup<input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="LR-1 / MB-2" autoCapitalize="characters"/></label></section>{lookup.trim()&&<section className="card matches"><h2>Lookup results / 查找结果</h2>{matches.map(row=><Link key={row.item.id} href={`/field-measure?window=${row.item.id}`}><b>{row.item.code}</b><span>{row.room.name}</span><small>{status(row)}</small></Link>)}{!matches.length&&<p>当前 Property 没有匹配 Window / No matching Window in this Property</p>}</section>}<section className={`card summary ${blockers?"blocked":"ready"}`}><div><small>{property?.name||"Property"}</small><h2>{blockers?"暂不可离场 / Not ready to leave":"可以离场 / Ready to leave"}</h2></div><b>{blockers} blocker(s)</b><span>{rooms.length} rooms · {rows.length} windows</span></section><section className="card checklist">{rooms.map(room=><article key={room.id}><h2>{room.name}</h2>{!room.windows.length&&<p className="missing">房间尚无 Window / No Window recorded</p>}{rows.filter(row=>row.room.id===room.id).map(row=><div className={row.complete&&!row.draft?"complete":"blocked"} key={row.item.id}><span>{row.complete&&!row.draft?"✓":"!"}</span><div><b>{row.item.code}</b><small>{status(row)}</small></div><div className="actions"><Link href={`/field-measure?window=${row.item.id}`}>Measure</Link>{row.latest&&<Link href={`/field-measure-media?window=${row.item.id}`}>Photos</Link>}</div></div>)}</article>)}</section><p className="truth">“可以离场”仅代表每个已登记 Window 的服务器最新测量满足产品必填规则、已绑定至少一张现场照片，且设备没有待同步草稿；不代表 Owner 已批准或生产已放行。</p><style jsx>{styles}</style></main>
}
const styles=`main{min-height:100vh;background:#f3f0e9;color:#173c31;padding:18px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.message,.truth{max-width:1050px;margin-left:auto;margin-right:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:22px;display:flex;justify-content:space-between;gap:16px}header h1{margin:6px 0}header p{margin:0;color:#cad9d3}nav,.actions{display:flex;gap:8px}a{border-radius:9px;padding:10px 13px;background:#ddb158;color:#173f35;text-decoration:none;font-weight:800}.message{margin-top:12px;background:#e5efe9;padding:11px}.card{background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px;margin-top:14px}.controls{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:6px;font-size:12px;font-weight:800}select,input{width:100%;box-sizing:border-box;border:1px solid #bdc9c3;border-radius:9px;padding:11px;font:inherit}.matches{display:grid;gap:8px}.matches h2{margin:0}.matches a{display:grid;grid-template-columns:120px 1fr 2fr;background:#eef3ef}.summary{display:flex;justify-content:space-between;align-items:center}.summary h2{margin:5px 0}.summary.blocked{border-left:8px solid #bd5d45}.summary.ready{border-left:8px solid #2d7d58}.checklist article{border-top:1px solid #e6e2d8;padding:12px 0}.checklist article:first-child{border-top:0}.checklist article>div{display:grid;grid-template-columns:30px 1fr auto;gap:10px;align-items:center;padding:10px;border-radius:10px;margin-top:7px}.checklist article>div.complete{background:#e8f3ec}.checklist article>div.blocked{background:#fff0e8}.checklist article>div>span{font-size:20px;font-weight:900}.checklist article>div>div:not(.actions){display:grid}.checklist article a{padding:8px}.missing,.truth{color:#6f7974}.truth{font-size:12px;margin-top:12px}@media(max-width:700px){main{padding:9px}header,.summary{display:grid}.controls{grid-template-columns:1fr}.matches a{grid-template-columns:1fr}.checklist article>div{grid-template-columns:28px 1fr}.actions{grid-column:2;flex-wrap:wrap}nav{flex-wrap:wrap}}`;
