"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {encryptedGet,encryptedPut} from "@/lib/offline-measure-device";
import {requiredMeasureFields} from "@/lib/measure-product-requirements";

type Value={fieldKey:string;totalSixteenths:number};type Version={id:number;version:number;status:string;productType:string;mountType:string;mediaCount:number;values:Value[]};type Win={id:number;code:string;versions:Version[]};type Room={id:number;name:string;windows:Win[]};type Property={id:number;name:string;address:string;rooms:Room[]};type Workspace={properties:Property[];cachedAt:string};type Draft={id:string;propertyId:number;windowId:number;windowCode:string;reviewed?:boolean;queuedAt:string};
const toleranceSixteenths=8,threePointGroups=[["width_left","width_center","width_right"],["height_left","height_center","height_right"]];
const fieldLabels:Record<string,string>={width_left:"左侧宽度 / Width left",width_center:"中间宽度 / Width center",width_right:"右侧宽度 / Width right",height_left:"左侧高度 / Height left",height_center:"中间高度 / Height center",height_right:"右侧高度 / Height right",depth:"深度 / Depth",ceiling_height:"天花高度 / Ceiling height",sill_height:"窗台高度 / Sill height",floor_clearance:"离地间隙 / Floor clearance",handle_projection:"把手突出 / Handle projection",return_left:"左侧回位 / Left return",return_right:"右侧回位 / Right return",overlap_left:"左侧重叠 / Left overlap",overlap_right:"右侧重叠 / Right overlap",stack_back_left:"左侧收帘空间 / Left stack back",stack_back_right:"右侧收帘空间 / Right stack back"};

export default function FieldMeasureAudit(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[propertyId,setPropertyId]=useState(0),[lookup,setLookup]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const cached=await encryptedGet<Workspace>("workspace"),queued=await encryptedGet<Draft[]>("drafts");if(cached)setWorkspace(cached);if(queued)setDrafts(queued);try{const response=await fetch("/api/v4/measure/workspace",{cache:"no-store"});if(response.status===401){location.href="/login";return}if(!response.ok)throw new Error();const data=await response.json(),fresh={properties:data.properties||[],cachedAt:new Date().toISOString()};await encryptedPut("workspace",fresh);setWorkspace(fresh);setMessage("已使用服务器最新工作区复核 / Reviewing latest server workspace")}catch{setMessage(cached?"离线复核设备加密缓存 / Auditing encrypted offline cache":"首次使用需要联网下载工作区 / Connect once to download workspace")}};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const properties=workspace?.properties||[],pid=properties.some(item=>item.id===propertyId)?propertyId:properties[0]?.id||0,property=properties.find(item=>item.id===pid),rooms=property?.rooms||[],rows=rooms.flatMap(room=>room.windows.map(item=>{const latest=item.versions?.[0],keys=new Set(latest?.values?.map(value=>value.fieldKey)||[]),missing=latest?requiredMeasureFields(latest.productType,latest.mountType).filter(key=>!keys.has(key)):[],map=new Map(latest?.values?.map(value=>[value.fieldKey,value.totalSixteenths])||[]),spread=threePointGroups.reduce((largest,group)=>{const values=group.map(key=>map.get(key)).filter((value):value is number=>value!==undefined);return values.length===3?Math.max(largest,Math.max(...values)-Math.min(...values)):largest},0),draft=drafts.find(candidate=>candidate.windowId===item.id),hasPhoto=Boolean(latest?.mediaCount),complete=Boolean(latest&&!missing.length&&hasPhoto&&spread<=toleranceSixteenths);return {room,item,latest,draft,missing,hasPhoto,spread,complete}})),matches=lookup.trim()?rows.filter(row=>row.item.code.toUpperCase().includes(lookup.trim().toUpperCase())):[],blockers=rows.filter(row=>!row.complete||row.draft).length+rooms.filter(room=>!room.windows.length).length;
 const status=(row:typeof rows[number])=>row.draft?(row.draft.reviewed?"已复核草稿，等待同步 / Reviewed draft pending sync":"草稿待复核 / Draft review required"):!row.latest?"尚未测量 / Measurement missing":row.missing.length?`V${row.latest.version} 缺少 / Missing: ${row.missing.map(key=>fieldLabels[key]||key).join(" · ")}`:row.spread>toleranceSixteenths?`V${row.latest.version} 三点最大差异 ${row.spread}/16，超过允许的 ${toleranceSixteenths}/16 / Three-point spread ${row.spread}/16 exceeds ${toleranceSixteenths}/16`:!row.hasPhoto?`V${row.latest.version} 缺少现场照片 / Site photo required`:`服务器 V${row.latest.version} 记录完整 / Server V${row.latest.version} complete`;
 return <main><header><div><small>SPRINT 16.1 · #246</small><h1>现场离开前复核 / Field Exit Audit</h1><p>逐个检查真实房间和窗位。设备草稿、产品必填尺寸或精确版本照片缺失都会阻止“可以离场”。/ Review every real Room and Window before leaving the site.</p></div><nav><Link href="/field-measure">测量 / Measure</Link><Link href="/field-measure-media">照片 / Photos</Link><Link href="/hub">工作中心 / Hub</Link></nav></header>{message&&<p className="message">{message}</p>}<section className="card controls"><label>房屋/项目 / Property<select value={pid} onChange={e=>{setPropertyId(+e.target.value);setLookup("")}}>{properties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>窗位编号查找 / Window code lookup<input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="例如 / Example: LR-1 · MB-2" autoCapitalize="characters"/></label></section>{lookup.trim()&&<section className="card matches"><h2>查找结果 / Lookup results</h2>{matches.map(row=><Link key={row.item.id} href={`/field-measure?window=${row.item.id}`}><b>{row.item.code}</b><span>{row.room.name}</span><small>{status(row)}</small></Link>)}{!matches.length&&<p>当前房屋/项目没有匹配窗位 / No matching Window in this Property</p>}</section>}<section className={`card summary ${blockers?"blocked":"ready"}`}><div><small>{property?.name||"房屋/项目 / Property"}</small><h2>{blockers?"暂不可离场 / Not ready to leave":"可以离场 / Ready to leave"}</h2></div><b>{blockers} 个阻塞项 / blocker(s)</b><span>{rooms.length} 个房间 / rooms · {rows.length} 个窗位 / windows</span></section><section className="card checklist">{rooms.map(room=><article key={room.id}><h2>{room.name}</h2>{!room.windows.length&&<p className="missing">房间尚无窗位记录 / No Window recorded in this Room</p>}{rows.filter(row=>row.room.id===room.id).map(row=><div className={row.complete&&!row.draft?"complete":"blocked"} key={row.item.id}><span>{row.complete&&!row.draft?"✓":"!"}</span><div><b>{row.item.code}</b><small>{status(row)}</small></div><div className="actions"><Link href={`/field-measure?window=${row.item.id}`}>测量 / Measure</Link>{row.latest&&<Link href={`/field-measure-media?window=${row.item.id}`}>照片 / Photos</Link>}</div></div>)}</article>)}</section><p className="truth">“可以离场”仅代表每个已登记窗位的服务器最新测量满足产品必填规则、已绑定至少一张现场照片，且设备没有待同步草稿；不代表老板已批准或生产已放行。/ “Ready to leave” confirms field completeness only; it is not Owner approval or production release.</p><style jsx>{styles}</style></main>
}
const styles=`main{min-height:100vh;background:#f3f0e9;color:#173c31;padding:18px;font-family:Arial,"PingFang SC",sans-serif}header,.card,.message,.truth{max-width:1050px;margin-left:auto;margin-right:auto;box-sizing:border-box}header{background:#153f34;color:white;border-radius:20px;padding:22px;display:flex;justify-content:space-between;gap:16px}header h1{margin:6px 0}header p{margin:0;color:#cad9d3}nav,.actions{display:flex;gap:8px}a{border-radius:9px;padding:10px 13px;background:#ddb158;color:#173f35;text-decoration:none;font-weight:800}.message{margin-top:12px;background:#e5efe9;padding:11px}.card{background:white;border:1px solid #ddd7ca;border-radius:16px;padding:18px;margin-top:14px}.controls{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:6px;font-size:12px;font-weight:800}select,input{width:100%;box-sizing:border-box;border:1px solid #bdc9c3;border-radius:9px;padding:11px;font:inherit}.matches{display:grid;gap:8px}.matches h2{margin:0}.matches a{display:grid;grid-template-columns:120px 1fr 2fr;background:#eef3ef}.summary{display:flex;justify-content:space-between;align-items:center}.summary h2{margin:5px 0}.summary.blocked{border-left:8px solid #bd5d45}.summary.ready{border-left:8px solid #2d7d58}.checklist article{border-top:1px solid #e6e2d8;padding:12px 0}.checklist article:first-child{border-top:0}.checklist article>div{display:grid;grid-template-columns:30px 1fr auto;gap:10px;align-items:center;padding:10px;border-radius:10px;margin-top:7px}.checklist article>div.complete{background:#e8f3ec}.checklist article>div.blocked{background:#fff0e8}.checklist article>div>span{font-size:20px;font-weight:900}.checklist article>div>div:not(.actions){display:grid}.checklist article a{padding:8px}.missing,.truth{color:#6f7974}.truth{font-size:12px;margin-top:12px}@media(max-width:700px){main{padding:9px}header,.summary{display:grid}.controls{grid-template-columns:1fr}.matches a{grid-template-columns:1fr}.checklist article>div{grid-template-columns:28px 1fr}.actions{grid-column:2;flex-wrap:wrap}nav{flex-wrap:wrap}}`;